/* ============================================================
   views/request-detail.js — request review + role-specific actions
   ============================================================ */
(function () {
    window.Views = window.Views || {};
    const esc = (s) => window.UI.esc(s);

    /* ---- definition cards ---- */
    function defRow(label, val, span) {
        return `<div class="def-row ${span ? 'span-2' : ''}"><div class="def-k">${esc(label)}</div><div class="def-v">${esc((val === undefined || val === null || val === '') ? '—' : val)}</div></div>`;
    }
    function defCard(title, rowsHtml) {
        return `<div class="panel-card"><div class="pc-title">${esc(title)}</div><div class="def-grid">${rowsHtml}</div></div>`;
    }

    function dataCards(p) {
        const attrs = Object.entries(p.attributes || {});
        return `
            ${defCard('Item identification',
                defRow('Short name', p.shortName) +
                defRow('Material Type', p.materialType || 'ROH') +
                defRow('Long description', p.longDesc, true))}
            ${defCard('Classification',
                defRow('Material Group', p.materialGroup ? p.materialGroup + ' — ' + window.UI.groupDesc(p.materialGroup) : '') +
                defRow('Material Description', p.materialDescription || window.UI.groupDesc(p.materialGroup)) +
                defRow('Category · UNSPSC', p.unspsc ? (p.unspscLabel || '') + ' · ' + p.unspsc : '') +
                defRow('Material type', p.matTypeChoice) +
                defRow('Manufacturer', p.manufacturer) +
                defRow('Manufacturer part #', p.mfrPartNo))}
            ${defCard('Logistics & planning',
                defRow('Plants', (p.plants && p.plants.length) ? p.plants.map(pc => window.UI.plantLabel(pc)).join(', ') : (p.plant ? window.UI.plantLabel(p.plant) : '')) +
                defRow('Storage location', p.storageLocation) +
                defRow('Base UoM', p.baseUom) +
                defRow('MRP planning enabled', p.mrpEnabled) +
                defRow('Batch-managed', p.batchManaged) +
                defRow('MRP type', p.mrpType) +
                defRow('Record type', p.recordType) +
                defRow('Valuation class', p.valuationClass ? p.valuationClass + ' — ' + window.UI.valuationDesc(p.valuationClass) : ''))}
            ${attrs.length ? defCard('Technical attributes', attrs.map(([k, v]) => defRow(k, v)).join('')) : ''}
            ${p.inventory ? `<div class="panel-card"><div class="pc-title">Inventory planning</div>${window.UI.inventoryRows(p.inventory)}</div>` : ''}`;
    }

    /* ---- new-category request: read-only proposal cards ---- */
    function categoryCards(p) {
        const attrs = p.catAttributes || [];
        return `
            ${defCard('Proposed category',
                defRow('Category name', p.categoryName) +
                defRow('UNSPSC code', p.unspsc) +
                (p.sourceText ? defRow('Searched item', p.sourceText, true) : ''))}
            <div class="panel-card"><div class="pc-title">Proposed attributes</div>
                ${attrs.length ? `<table class="data-table attr-table">
                    <thead><tr><th>Attribute name</th><th>Field type</th><th>UoM</th><th>Mandatory</th><th>List values</th></tr></thead>
                    <tbody>${attrs.map(a => `<tr>
                        <td style="font-weight:600">${esc(a.name)}</td><td>${esc(a.fieldType || 'Text')}</td>
                        <td>${esc(a.uom || '—')}</td><td>${a.mandatory ? 'Yes' : 'No'}</td><td>${esc(a.options || '—')}</td>
                    </tr>`).join('')}</tbody></table>` : '<div class="muted">No attributes proposed.</div>'}
            </div>`;
    }

    // MDM editable fields
    function editableGrid(p) {
        const F = window.UI.field, ds = window.Store.get().datasets;
        return `<div class="form-grid" id="mdm-edit">
            ${F({ label: 'Short name', name: 'shortName', value: p.shortName, span: 2 })}
            ${F({ label: 'Long description', name: 'longDesc', type: 'textarea', value: p.longDesc, span: 3, readonly: true, hint: 'Generated by the AI engine — not editable' })}
            ${F({ label: 'Material Group', name: 'materialGroup', type: 'select', value: p.materialGroup, options: ds.MATERIAL_GROUPS.map(g => ({ value: g.code, label: g.code + ' — ' + g.desc })) })}
            ${F({ label: 'UNSPSC code', name: 'unspsc', value: p.unspsc })}
            ${F({ label: 'Category', name: 'unspscLabel', value: p.unspscLabel })}
            ${F({ label: 'Manufacturer', name: 'manufacturer', value: p.manufacturer })}
            ${F({ label: 'Manufacturer part #', name: 'mfrPartNo', value: p.mfrPartNo })}
            ${F({ label: 'Material type', name: 'matTypeChoice', type: 'select', value: p.matTypeChoice, options: ds.MATERIAL_TYPE_CHOICES })}
            ${F({ label: 'Base UoM', name: 'baseUom', type: 'select', value: p.baseUom, options: ds.UOM })}
            ${F({ label: 'Storage location', name: 'storageLocation', type: 'select', value: p.storageLocation, options: window.UI.storageOptionsFor((p.plants && p.plants[0]) || p.plant) })}
            ${F({ label: 'MRP type', name: 'mrpType', type: 'select', value: p.mrpType, options: ds.MRP_TYPES })}
        </div>`;
    }
    function collectEdits(root) {
        const edits = {};
        root.querySelectorAll('#mdm-edit [name]').forEach(el => { edits[el.getAttribute('name')] = el.value; });
        return edits;
    }

    /* ---------------- Inventory team stage ---------------- */
    function renderInventoryPanel(root, req, zone) {
        const F = window.UI.field, ds = window.Store.get().datasets;
        const p = req.payload;
        const inv = p.inventory || {};
        zone.innerHTML = `
            <div class="result-block">
                <div class="rb-title" style="margin-bottom:4px">Inventory setup (Inventory team)</div>
                <div class="muted" style="margin-bottom:14px">The record is live in SAP (ID ${esc(req.sapId)}). Fill in the inventory planning data and submit.</div>
                <form id="inv-form"><div class="form-grid">
                    ${F({ label: 'Material (Material Master Record)', name: 'inv::material', value: req.sapId, readonly: true, hint: 'SAP ID (auto)' })}
                    ${F({ label: 'Plant', name: 'inv::plant', value: req.requesterPlant, readonly: true, hint: 'Auto' })}
                    ${F({ label: 'MRP Group', name: 'inv::mrpGroup', value: p.materialGroup, readonly: true, hint: "From item's data" })}
                    ${F({ label: 'ABC Code', name: 'inv::abcCode', type: 'select', value: inv.abcCode, options: ds.ABC_CODES, required: true })}
                    ${F({ label: 'MRP Type', name: 'inv::mrpType', type: 'select', value: inv.mrpType || p.mrpType, options: ds.MRP_TYPES, required: true, hint: "Auto from item, changeable" })}
                    ${F({ label: 'Reorder point', name: 'inv::reorderPoint', value: inv.reorderPoint, hint: 'Required for Z1+R, VB+N, VB+G' })}
                    ${F({ label: 'MRP Controller — Min qty', name: 'inv::mrpControllerMin', value: inv.mrpControllerMin, required: true, hint: 'Numeric' })}
                    ${F({ label: 'MRP Controller — Max qty', name: 'inv::mrpControllerMax', value: inv.mrpControllerMax, required: true, hint: 'Numeric' })}
                    ${F({ label: 'Lot-size', name: 'inv::lotSize', type: 'select', value: inv.lotSize, options: ds.LOT_SIZES, required: true })}
                    ${F({ label: 'Fixed lot size', name: 'inv::fixedLotSize', value: inv.fixedLotSize, hint: 'Required for Z1+R' })}
                    ${F({ label: 'Procurement Type', name: 'inv::procurementType', value: 'F', readonly: true, hint: 'Fixed' })}
                    ${F({ label: 'Planned Delivery Time (Days)', name: 'inv::plannedDeliveryDays', value: inv.plannedDeliveryDays, hint: 'Number of days' })}
                    ${F({ label: 'Safety Stock', name: 'inv::safetyStock', value: inv.safetyStock, hint: 'Required for Z1+R' })}
                </div></form>
                <div class="form-actions" style="margin-top:16px">
                    <button class="btn btn-green" data-act="submit-inv">Submit inventory data</button>
                </div>
            </div>`;

        window.UI.bindActions(zone, {
            'submit-inv': () => {
                const data = collectInventory(zone);
                data.procurementType = 'F';
                const res = validateInventory(data);
                zone.querySelectorAll('.form-input, .form-select').forEach(el => el.classList.remove('error'));
                zone.querySelectorAll('.field-error').forEach(el => el.textContent = '');
                if (!res.ok) {
                    res.errors.forEach(er => {
                        const el = zone.querySelector(`[name="inv::${er.field}"]`); if (el) el.classList.add('error');
                        const errEl = zone.querySelector(`[data-err="inv::${er.field}"]`); if (errEl) errEl.textContent = er.msg;
                    });
                    window.UI.toast({ title: 'Cannot submit', body: 'Some mandatory inventory fields are blank.', kind: 'danger' });
                    return;
                }
                window.Workflow.act(req, 'approve', { inventory: data });
                window.UI.toast({ title: 'Inventory data submitted', body: 'Request completed.', kind: 'info' });
                window.Views.requestDetail(req.id);
            }
        });
    }

    /* ---------------- Central team: new-category review ---------------- */
    function renderCategoryReview(root, req, zone) {
        zone.innerHTML = `
            <div class="result-block">
                <div class="rb-title" style="margin-bottom:4px">Your review — Steward review (Central team)</div>
                <div class="muted" style="margin-bottom:14px">Review the proposed category. You may adjust the UNSPSC code, the category name and the attributes before approving. On approval the category and its attributes are added to the category catalogue.</div>
                <div id="cat-review-editor">${window.UI.categoryEditorHtml(req.payload)}</div>
                <div class="field" style="margin:16px 0 14px">
                    <label>Comment</label>
                    <textarea class="form-textarea" id="review-comment" placeholder="Add a note…"></textarea>
                </div>
                <div class="form-actions">
                    <button class="btn btn-green" data-act="approve">Approve & add to catalog</button>
                    <button class="btn btn-danger-outline" data-act="decline">Decline</button>
                </div>
            </div>`;
        const ed = zone.querySelector('#cat-review-editor');
        window.UI.bindCategoryEditor(ed);
        window.UI.bindActions(zone, {
            'approve': () => {
                const data = window.UI.collectCategoryEditor(ed);
                if (!window.UI.validateCategoryEditor(ed, data)) { window.UI.toast({ title: 'Cannot approve', body: 'Please complete the category details.', kind: 'danger' }); return; }
                const comment = (zone.querySelector('#review-comment') || {}).value || '';
                window.Workflow.act(req, 'approve', { comment, edits: data });
                window.UI.toast({ title: 'Category added to the catalog', body: `“${data.categoryName}” (UNSPSC ${data.unspsc}) is now available.`, kind: 'info' });
                window.Views.requestDetail(req.id);
            },
            'decline': () => doDecline(req, zone, 'decline')
        });
    }

    function collectInventory(zone) {
        const inv = {};
        zone.querySelectorAll('#inv-form [name^="inv::"]').forEach(el => { inv[el.getAttribute('name').slice(5)] = el.value.trim(); });
        return inv;
    }

    // mandatory: ABC Code, MRP Type, MRP Controller min & max, Lot-size.
    // conditional: Z1+R → reorder point, fixed lot size, safety stock; VB+N and VB+G → reorder point.
    function validateInventory(inv) {
        const errors = [];
        const req = (k, label) => { if (!inv[k] || String(inv[k]).trim() === '') errors.push({ field: k, msg: (label || k) + ' is required.' }); };
        req('abcCode', 'ABC Code');
        req('mrpType', 'MRP Type');
        req('mrpControllerMin', 'MRP Controller — Min qty');
        req('mrpControllerMax', 'MRP Controller — Max qty');
        req('lotSize', 'Lot-size');
        const z1r = inv.mrpType === 'Z1' && inv.abcCode === 'R';
        const vbn = inv.mrpType === 'VB' && inv.abcCode === 'N';
        const vbg = inv.mrpType === 'VB' && inv.abcCode === 'G';
        if (z1r || vbn || vbg) req('reorderPoint', 'Reorder point');
        if (z1r) { req('fixedLotSize', 'Fixed lot size'); req('safetyStock', 'Safety Stock'); }
        return { ok: errors.length === 0, errors };
    }

    window.Views.requestDetail = function (id) {
        const req = window.Store.requestById(id);
        const root = document.getElementById('view');
        if (!req) { root.innerHTML = `<div class="page-narrow"><div class="empty-state">Request not found.</div></div>`; return; }

        const s = window.Store.session();
        const stage = window.Workflow.currentStage(req);
        const awaitingMe = window.Workflow.isAwaiting(req, s.currentRole);
        const isMyRequest = req.requesterUser === s.currentUser && s.currentRole === 'Requester';
        const statusCls = req.status === 'Completed' ? 'completed' : (req.status === 'Approved' ? 'approved' : (req.status === 'Declined' ? 'declined' : (req.status === 'Draft' ? 'draft' : 'in-review')));

        const feedback = (req.aiFeedback && req.aiFeedback.length)
            ? `<div class="banner warn"><span class="banner-icon">✦</span><div class="banner-body">
                <div class="banner-title">AI feedback captured at submission</div>
                <ul style="margin:6px 0 0 18px">${req.aiFeedback.map(w => `<li>${esc(w.msg)}</li>`).join('')}</ul></div></div>` : '';

        const p = req.payload;
        const noImg = `<svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="#C9CCC6" stroke-width="1.5"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/></svg>`;
        const stageNow = req.status === 'Draft' ? 'Not submitted'
            : (req.status === 'Declined' ? 'Returned to requester'
            : (req.status === 'Completed' ? 'All steps completed'
            : (stage ? stage.label + ' — ' + stage.role : '—')));

        root.innerHTML = `
            <div class="sub-header"><span class="crumb-link" data-act="home">Material Master</span> ›
                <span class="crumb-link" data-act="back">Requests</span> › ${esc(window.Workflow.reqNo(req))}</div>
            <div class="page-full">
                <div class="req-head">
                    <div>
                        <div class="req-eyebrow">${esc(window.Workflow.typeLabel(req.type))} · ${esc(window.Workflow.reqNo(req))}</div>
                        <h1 class="req-title">${esc(p.shortName || req.title)}</h1>
                    </div>
                    <div class="req-head-right">
                        <span class="status-pill ${statusCls}">${esc(req.status)}</span>
                        ${req.sapId ? `<span class="sap-chip">SAP ID ${esc(req.sapId)}</span>` : ''}
                    </div>
                </div>

                <div class="panel-card tracker-card">${window.UI.workflowTracker(req)}</div>
                ${feedback}

                <div class="req-layout">
                    <div class="req-main">
                        <div id="action-zone"></div>
                        <div id="data-zone">${req.type === 'category' ? categoryCards(p) : dataCards(p)}</div>
                    </div>
                    <aside class="req-side">
                        <div class="panel-card">
                            <div class="pc-title">Summary</div>
                            ${req.type === 'category' ? '' : `<div class="side-photo">${p.image ? `<img src="${esc(p.image)}" alt="Item photo">` : noImg}</div>`}
                            <div class="def-grid one-col">
                                ${defRow('Current stage', stageNow)}
                                ${defRow('Requester', req.requesterUser)}
                                ${defRow('Plant', req.requesterPlant + ' — ' + window.UI.plantName(req.requesterPlant))}
                                ${defRow('Created', window.UI.nowLabel(req.createdTs))}
                                ${req.sapId ? defRow('SAP ID', req.sapId) : ''}
                            </div>
                            ${req.materialId || req.sapId ? `<button class="btn btn-green-outline btn-sm" style="width:100%;margin-top:12px" data-act="view-item">View material record</button>` : ''}
                        </div>
                        <div class="panel-card">
                            <div class="pc-title">Activity</div>
                            ${window.UI.historyList(req)}
                        </div>
                    </aside>
                </div>
            </div>`;

        renderActionZone(root, req, stage, awaitingMe, isMyRequest);

        window.UI.bindActions(root, {
            'home': () => window.UI.go('#/master'),
            'back': () => window.UI.go('#/inbox'),
            'view-item': () => {
                const mid = req.materialId || (window.Store.materials().find(m => m.sapId === req.sapId) || {}).id;
                if (mid) window.UI.go('#/item/' + mid);
            }
        });
    };

    function renderActionZone(root, req, stage, awaitingMe, isMyRequest) {
        const zone = root.querySelector('#action-zone');

        // Requester view of a declined request → edit & resubmit
        if (isMyRequest && req.status === 'Declined') {
            const lastDecline = [...req.history].reverse().find(h => h.action === 'declined');
            if (req.type === 'category') {
                zone.innerHTML = `<div class="banner danger"><span class="banner-icon">↩️</span><div class="banner-body">
                        <div class="banner-title">Declined by ${esc(lastDecline ? lastDecline.actorRole : 'reviewer')} — please fix and resubmit</div>
                        ${lastDecline && lastDecline.comment ? '“' + esc(lastDecline.comment) + '”' : 'Please review and resubmit.'}</div></div>
                    <div class="result-block" style="margin-top:14px">
                        <div class="rb-title" style="margin-bottom:10px">Fix your category proposal</div>
                        <div id="cat-fix-editor">${window.UI.categoryEditorHtml(req.payload)}</div>
                        <div class="form-actions" style="margin-top:16px"><button class="btn btn-green" data-act="resubmit-cat">Resubmit request</button></div>
                    </div>`;
                const ed = zone.querySelector('#cat-fix-editor');
                window.UI.bindCategoryEditor(ed);
                window.UI.bindActions(zone, {
                    'resubmit-cat': () => {
                        const data = window.UI.collectCategoryEditor(ed);
                        if (!window.UI.validateCategoryEditor(ed, data)) { window.UI.toast({ title: 'Cannot resubmit', body: 'Please complete the category details.', kind: 'danger' }); return; }
                        window.Workflow.resubmit(req, Object.assign({ name: data.categoryName, shortName: data.categoryName }, data));
                        window.UI.toast({ title: 'Resubmitted', body: 'Your category proposal is back with the Central team.' });
                        window.Views.requestDetail(req.id);
                    }
                });
                return;
            }
            zone.innerHTML = `<div class="banner danger"><span class="banner-icon">↩️</span><div class="banner-body">
                    <div class="banner-title">Declined by ${esc(lastDecline ? lastDecline.actorRole : 'reviewer')} — please fix and resubmit</div>
                    ${lastDecline && lastDecline.comment ? '“' + esc(lastDecline.comment) + '”' : 'Please review and resubmit.'}</div>
                <div class="banner-actions">
                    ${req.type === 'create' || req.type === 'amend' ? `<button class="btn btn-green btn-sm" data-act="edit-resubmit">Edit & resubmit</button>` : `<button class="btn btn-green btn-sm" data-act="resubmit">Resubmit</button>`}
                </div></div>`;
            window.UI.bindActions(zone, {
                'edit-resubmit': () => {
                    window.Views._draft = { type: req.type, payload: req.payload, materialId: req.materialId,
                        resubmitId: req.id, analysis: { known: true } };
                    window.UI.go('#/request/new?type=' + req.type);
                },
                'resubmit': () => { window.Workflow.resubmit(req); window.UI.toast({ title: 'Resubmitted', body: 'Back in review.' }); window.Views.requestDetail(req.id); }
            });
            return;
        }

        // Draft owned by requester
        if (isMyRequest && req.status === 'Draft') {
            zone.innerHTML = `<div class="banner info"><span class="banner-icon">📝</span><div class="banner-body">This request is a draft.</div>
                <div class="banner-actions">
                    <button class="btn btn-green btn-sm" data-act="edit-draft">Continue editing</button>
                    <button class="btn btn-danger-outline btn-sm" data-act="delete-draft">Delete draft</button>
                </div></div>`;
            window.UI.bindActions(zone, {
                'edit-draft': () => {
                    window.Views._draft = { type: req.type, payload: req.payload, materialId: req.materialId, resubmitId: req.id, analysis: { known: true } };
                    window.UI.go('#/request/new?type=' + req.type);
                },
                'delete-draft': () => confirmDeleteDraft(req, () => window.UI.go('#/inbox'))
            });
            return;
        }

        if (req.status === 'Completed') {
            if (req.type === 'category') {
                const p = req.payload;
                const central = window.Store.session().currentRole === 'Central team';
                zone.innerHTML = `<div class="banner match"><span class="banner-icon">✓</span><div class="banner-body">
                    <div class="banner-title">Category added to the catalog</div>“${esc(p.categoryName)}” (UNSPSC ${esc(p.unspsc)}) with ${(p.catAttributes || []).length} attributes is now available for item classification.</div>
                    ${central ? `<div class="banner-actions"><button class="btn btn-green-outline btn-sm" data-act="view-catalog">View category catalogue</button></div>` : ''}</div>`;
                window.UI.bindActions(zone, { 'view-catalog': () => window.UI.go('#/categories') });
                return;
            }
            zone.innerHTML = `<div class="banner match"><span class="banner-icon">✓</span><div class="banner-body">
                <div class="banner-title">Completed</div>SAP responded with ID <strong>${esc(req.sapId)}</strong>. The material record has been ${verb(req.type)}.</div>
                ${req.materialId || true ? `<div class="banner-actions"><button class="btn btn-green-outline btn-sm" data-act="view-item">View record</button></div>` : ''}</div>`;
            window.UI.bindActions(zone, { 'view-item': () => {
                const mid = req.materialId || (window.Store.materials().find(m => m.sapId === req.sapId) || {}).id;
                if (mid) window.UI.go('#/item/' + mid);
            }});
            return;
        }

        if (!awaitingMe) {
            const st = window.Workflow.currentStage(req);
            // SAP done, item approved & live — only the Inventory task remains open
            if (req.status === 'Approved') {
                zone.innerHTML = `<div class="banner match"><span class="banner-icon">✓</span><div class="banner-body">
                    <div class="banner-title">Item approved</div>SAP responded with ID <strong>${esc(req.sapId)}</strong> — the record is live in the material master.
                    Inventory setup by the <strong>Inventory team</strong> is still pending, but does not hold the item.</div>
                    <div class="banner-actions"><button class="btn btn-green-outline btn-sm" data-act="view-item">View record</button></div></div>`;
                window.UI.bindActions(zone, { 'view-item': () => {
                    const mid = req.materialId || (window.Store.materials().find(m => m.sapId === req.sapId) || {}).id;
                    if (mid) window.UI.go('#/item/' + mid);
                }});
                return;
            }
            zone.innerHTML = `<div class="banner info"><span class="banner-icon">⏳</span><div class="banner-body">
                Awaiting <strong>${esc(st ? st.role : '')}</strong> (${esc(st ? st.label : '')}). ${window.Store.session().currentRole === 'Requester' ? 'You will be notified when it progresses.' : 'You are acting as ' + esc(window.Store.session().currentRole) + '; switch role to act on this.'}</div></div>`;
            return;
        }

        // ---- Inventory team: post-SAP inventory setup form ----
        if (stage.key === 'inventory') { renderInventoryPanel(root, req, zone); return; }

        // ---- Central team: new-category review (editable proposal) ----
        if (req.type === 'category' && stage.key === 'central') { renderCategoryReview(root, req, zone); return; }

        // ---- awaiting the current role: render the action panel ----
        const ds = window.Store.get().datasets;
        let extra = '';
        if (stage.key === 'finance') {
            extra = `<div class="field" style="max-width:420px;margin-bottom:14px">
                <label>Valuation Class <span class="req">*</span></label>
                <select class="form-select" id="valclass">
                    <option value="">Select valuation class…</option>
                    ${ds.VALUATION_CLASSES.map(v => `<option value="${v.code}">${v.code} — ${esc(v.desc)}</option>`).join('')}
                </select>
                <div class="field-error" id="valclass-err"></div></div>`;
        }
        if (stage.key === 'mdm') {
            extra = `<div class="banner info mb-0" style="margin-bottom:12px"><span class="banner-icon">✎</span><div class="banner-body">You may edit any field below before approving.</div></div>
                ${editableGrid(req.payload)}`;
        }

        // Finance only supplies the valuation class — it cannot decline
        const canDecline = stage.key !== 'finance';
        zone.innerHTML = `
            <div class="result-block">
                <div class="rb-title" style="margin-bottom:10px">Your review — ${esc(stage.label)} (${esc(stage.role)})</div>
                ${extra}
                <div class="field" style="margin-bottom:14px">
                    <label>Comment</label>
                    <textarea class="form-textarea" id="review-comment" placeholder="Add a note…"></textarea>
                </div>
                <div class="form-actions">
                    <button class="btn btn-green" data-act="approve">${stage.key === 'finance' ? 'Submit' : 'Approve'}</button>
                    ${canDecline ? '<button class="btn btn-danger-outline" data-act="decline">Decline</button>' : ''}
                </div>
            </div>`;

        window.UI.bindActions(zone, {
            'approve': () => {
                const comment = (zone.querySelector('#review-comment') || {}).value || '';
                const data = { comment };
                if (stage.key === 'finance') {
                    const vc = zone.querySelector('#valclass').value;
                    if (!vc) { zone.querySelector('#valclass-err').textContent = 'Valuation class is required.'; zone.querySelector('#valclass').classList.add('error'); return; }
                    data.valuationClass = vc;
                }
                if (stage.key === 'mdm') data.edits = collectEdits(root);
                window.Workflow.act(req, 'approve', data);
                window.UI.toast({ title: stage.key === 'finance' ? 'Submitted' : 'Approved', body: nextMsg(req), kind: 'info' });
                window.Views.requestDetail(req.id);
            },
            'decline': () => doDecline(req, zone, 'decline')
        });
    }

    // shared draft-delete confirmation (also used by the inbox)
    function confirmDeleteDraft(req, after) {
        window.UI.openModal({
            title: 'Delete draft',
            bodyHtml: `<p>Delete draft <strong>${esc(req.payload && req.payload.shortName || req.title)}</strong> (${esc(window.Workflow.reqNo(req))})?<br>
                <span class="muted">This cannot be undone.</span></p>`,
            buttons: [
                { label: 'Cancel', cls: 'btn-outline', onClick: (o) => o.remove() },
                { label: 'Delete draft', cls: 'btn-danger-outline', onClick: (o) => {
                    o.remove();
                    if (window.Workflow.deleteDraft(req.id)) {
                        window.UI.toast({ title: 'Draft deleted', body: req.payload && req.payload.shortName || req.title, kind: 'danger' });
                        if (after) after();
                    }
                } }
            ]
        });
    }
    window.Views.confirmDeleteDraft = confirmDeleteDraft;

    function doDecline(req, zone, action) {
        const comment = (zone.querySelector('#review-comment') || {}).value || '';
        if (!comment.trim()) {
            window.UI.toast({ title: 'Comment required', body: 'A comment is mandatory to ' + (action === 'correction' ? 'send back' : 'decline') + '.', kind: 'danger' });
            const ta = zone.querySelector('#review-comment'); if (ta) { ta.classList.add('error'); ta.focus(); }
            return;
        }
        window.Workflow.act(req, action, { comment });
        window.UI.toast({ title: action === 'correction' ? 'Sent for correction' : 'Declined', body: 'Returned to the requester.', kind: 'info' });
        window.Views.requestDetail(req.id);
    }

    function nextMsg(req) {
        if (req.status === 'Completed') return 'Request completed — SAP ID ' + req.sapId + '.';
        const st = window.Workflow.currentStage(req);
        return st ? 'Forwarded to ' + st.role + '.' : 'Advanced.';
    }
    function verb(type) {
        return { create: 'created', amend: 'updated', extend: 'extended to your plant', block: 'blocked at plant level',
            reactivate: 'reactivated', block_proc: 'blocked for procurement', block_total: 'totally blocked', unblock_central: 'unblocked',
            valuation: 'updated (valuation class)' }[type] || 'processed';
    }
})();
