/* ============================================================
   views/request-detail.js — request review + role-specific actions
   ============================================================ */
(function () {
    window.Views = window.Views || {};
    const esc = (s) => window.UI.esc(s);

    /* ---- definition cards ---- */
    function defRow(label, val, span) {
        return `<div class="def-row ${span ? 'span-2' : ''}"><div class="def-k">${esc(label)}</div><div class="def-v">${esc((val === undefined || val === null || val === '') ? '—' : val)}</div></div>`;
    }
    function defCard(title, rowsHtml) {
        return `<div class="panel-card"><div class="pc-title">${esc(title)}</div><div class="def-grid">${rowsHtml}</div></div>`;
    }

    function dataCards(p) {
        const attrs = Object.entries(p.attributes || {});
        return `
            ${defCard('Item identification',
                defRow('Short name', p.shortName) +
                defRow('Material Type', p.materialType || 'ROH') +
                defRow('Long description', p.longDesc, true))}
            ${defCard('Classification',
                defRow('Material Group', p.materialGroup ? p.materialGroup + ' — ' + window.UI.groupDesc(p.materialGroup) : '') +
                defRow('Material Description', p.materialDescription || window.UI.groupDesc(p.materialGroup)) +
                defRow('Category · UNSPSC', p.unspsc ? (p.unspscLabel || '') + ' · ' + p.unspsc : '') +
                defRow('Material type', p.matTypeChoice) +
                defRow('Manufacturer', p.manufacturer) +
                defRow('Manufacturer part #', p.mfrPartNo))}
            ${defCard('Logistics & planning',
                defRow('Plants', (p.plants && p.plants.length) ? p.plants.map(pc => window.UI.plantLabel(pc)).join(', ') : (p.plant ? window.UI.plantLabel(p.plant) : '')) +
                defRow('Storage location', p.storageLocation) +
                defRow('Base UoM', p.baseUom) +
                defRow('PO unit', p.poUnit) +
                defRow('MRP planning enabled', p.mrpEnabled) +
                defRow('Batch-managed', p.batchManaged) +
                defRow('MRP type', p.mrpType) +
                defRow('Record type', p.recordType) +
                defRow('Valuation class', p.valuationClass ? p.valuationClass + ' — ' + window.UI.valuationDesc(p.valuationClass) : ''))}
            ${attrs.length ? defCard('Technical attributes', attrs.map(([k, v]) => defRow(k, v)).join('')) : ''}
            ${(p.documents && p.documents.length) ? `<div class="panel-card"><div class="pc-title">Supporting documents</div>${window.UI.docListHtml(p.documents)}</div>` : ''}
            ${p.inventory ? `<div class="panel-card"><div class="pc-title">Inventory planning</div>${window.UI.inventoryRows(p.inventory)}</div>` : ''}`;
    }

    /* ---- new-category request: read-only proposal cards ---- */
    function categoryCards(p) {
        const attrs = p.catAttributes || [];
        return `
            ${defCard('Proposed category',
                defRow('Category name', p.categoryName) +
                defRow('UNSPSC code', p.unspsc) +
                (p.materialGroup ? defRow('Material group', p.materialGroup + (window.UI.groupDesc(p.materialGroup) ? ' — ' + window.UI.groupDesc(p.materialGroup) : '')) : '') +
                (p.sourceText ? defRow('Searched item', p.sourceText, true) : ''))}
            <div class="panel-card"><div class="pc-title">Proposed attributes</div>
                ${attrs.length ? `<table class="data-table attr-table">
                    <thead><tr><th>Attribute name</th><th>Field type</th><th>Measured in</th><th>Mandatory</th><th>List values</th></tr></thead>
                    <tbody>${attrs.map(a => `<tr>
                        <td style="font-weight:600">${esc(a.name)}</td><td>${esc(a.fieldType || 'Text')}</td>
                        <td>${esc(a.uom || '—')}</td><td>${a.mandatory ? 'Yes' : 'No'}</td><td>${esc(a.options || '—')}</td>
                    </tr>`).join('')}</tbody></table>` : '<div class="muted">No attributes proposed.</div>'}
            </div>`;
    }

    // MDM editable fields
    function editableGrid(p) {
        const F = window.UI.field, ds = window.Store.get().datasets;
        return `<div class="form-grid" id="mdm-edit">
            ${F({ label: 'Short name', name: 'shortName', value: p.shortName, span: 2, required: true })}
            ${F({ label: 'Long description', name: 'longDesc', type: 'textarea', value: p.longDesc, span: 3, required: true, readonly: true, hint: 'Generated by the AI engine — not editable' })}
            ${F({ label: 'Material Group', name: 'materialGroup', type: 'select', value: p.materialGroup, required: true, options: ds.MATERIAL_GROUPS.map(g => ({ value: g.code, label: g.code + ' — ' + g.desc })) })}
            ${F({ label: 'UNSPSC code', name: 'unspsc', value: p.unspsc, readonly: true, hint: 'Fixed by the item’s category — not editable' })}
            ${F({ label: 'Category', name: 'unspscLabel', value: p.unspscLabel })}
            ${F({ label: 'Manufacturer', name: 'manufacturer', value: p.manufacturer, hint: 'Mandatory for OEM' })}
            ${F({ label: 'Manufacturer part #', name: 'mfrPartNo', value: p.mfrPartNo, hint: 'Mandatory for OEM' })}
            ${F({ label: 'Material type', name: 'matTypeChoice', type: 'select', value: p.matTypeChoice, required: true, options: ds.MATERIAL_TYPE_CHOICES })}
            ${F({ label: 'Base UoM', name: 'baseUom', type: 'select', value: p.baseUom, required: true, options: ds.UOM })}
            ${F({ label: 'PO unit', name: 'poUnit', type: 'select', value: p.poUnit, required: true, options: ds.UOM, hint: 'Unit of measure for purchasing — assigned by MDM' })}
            ${F({ label: 'Storage location', name: 'storageLocation', type: 'select', value: p.storageLocation, required: true, options: window.UI.storageOptionsFor((p.plants && p.plants[0]) || p.plant) })}
            ${F({ label: 'MRP type', name: 'mrpType', type: 'select', value: p.mrpType, required: true, options: ds.MRP_TYPES })}
        </div>`;
    }
    function collectEdits(root) {
        const edits = {};
        root.querySelectorAll('#mdm-edit [name]').forEach(el => { edits[el.getAttribute('name')] = el.value; });
        return edits;
    }

    /* ---------------- Inventory team stage ---------------- */
    function renderInventoryPanel(root, req, zone) {
        const F = window.UI.field, ds = window.Store.get().datasets;
        const p = req.payload;
        const inv = p.inventory || {};
        zone.innerHTML = `
            <div class="result-block">
                <div class="rb-title" style="margin-bottom:4px">Inventory setup (Inventory team)</div>
                <div class="muted" style="margin-bottom:14px">The record is live in SAP (ID ${esc(req.sapId)}). Fill in the inventory planning data and submit.</div>
                <form id="inv-form"><div class="form-grid">
                    ${F({ label: 'Material (Material Master Record)', name: 'inv::material', value: req.sapId, readonly: true, hint: 'SAP ID (auto)' })}
                    ${F({ label: 'Plant', name: 'inv::plant', value: req.requesterPlant, readonly: true, hint: 'Auto' })}
                    ${F({ label: 'MRP Group', name: 'inv::mrpGroup', value: p.materialGroup, readonly: true, hint: "From item's data" })}
                    ${F({ label: 'ABC Code', name: 'inv::abcCode', type: 'select', value: inv.abcCode, options: ds.ABC_CODES, required: true })}
                    ${F({ label: 'MRP Type', name: 'inv::mrpType', type: 'select', value: inv.mrpType || p.mrpType, options: ds.MRP_TYPES, required: true, hint: "Auto from item, changeable" })}
                    ${F({ label: 'Reorder point', name: 'inv::reorderPoint', value: inv.reorderPoint, hint: 'Required for Z1+R, VB+N, VB+G' })}
                    ${F({ label: 'MRP Controller — Min qty', name: 'inv::mrpControllerMin', value: inv.mrpControllerMin, required: true, hint: 'Numeric' })}
                    ${F({ label: 'MRP Controller — Max qty', name: 'inv::mrpControllerMax', value: inv.mrpControllerMax, required: true, hint: 'Numeric' })}
                    ${F({ label: 'Lot-size', name: 'inv::lotSize', type: 'select', value: inv.lotSize, options: ds.LOT_SIZES, required: true })}
                    ${F({ label: 'Fixed lot size', name: 'inv::fixedLotSize', value: inv.fixedLotSize, hint: 'Required for Z1+R' })}
                    ${F({ label: 'Procurement Type', name: 'inv::procurementType', value: 'F', readonly: true, hint: 'Fixed' })}
                    ${F({ label: 'Planned Delivery Time (Days)', name: 'inv::plannedDeliveryDays', value: inv.plannedDeliveryDays, hint: 'Number of days' })}
                    ${F({ label: 'Safety Stock', name: 'inv::safetyStock', value: inv.safetyStock, hint: 'Required for Z1+R' })}
                </div></form>
                <div class="form-actions" style="margin-top:16px">
                    <button class="btn btn-green" data-act="submit-inv">Submit inventory data</button>
                </div>
            </div>`;

        window.UI.bindInvMinMaxRule(zone.querySelector('#inv-form'));

        window.UI.bindActions(zone, {
            'submit-inv': () => {
                const data = collectInventory(zone);
                data.procurementType = 'F';
                const res = validateInventory(data);
                zone.querySelectorAll('.form-input, .form-select').forEach(el => el.classList.remove('error'));
                zone.querySelectorAll('.field-error').forEach(el => el.textContent = '');
                if (!res.ok) {
                    res.errors.forEach(er => {
                        const el = zone.querySelector(`[name="inv::${er.field}"]`); if (el) el.classList.add('error');
                        const errEl = zone.querySelector(`[data-err="inv::${er.field}"]`); if (errEl) errEl.textContent = er.msg;
                    });
                    window.UI.toast({ title: 'Cannot submit', body: 'Some mandatory inventory fields are blank.', kind: 'danger' });
                    return;
                }
                window.Workflow.act(req, 'approve', { inventory: data });
                window.UI.toast({ title: 'Inventory data submitted', body: 'Request completed.', kind: 'info' });
                window.Views.requestDetail(req.id);
            }
        });
    }

    /* ---------------- BULK requests: items card + batch review ---------------- */
    function bulkItemName(req, it) {
        const p = it.payload;
        return req.type === 'category' ? (p.categoryName || '—') : (p.shortName || p.name || '—');
    }
    function bulkItemSub(req, it) {
        const p = it.payload;
        if (req.type === 'category') return 'UNSPSC ' + (p.unspsc || '—') + ' · ' + (p.catAttributes || []).length + ' attributes';
        if (req.type === 'extend') return 'Extend to plant ' + req.requesterPlant + ' — ' + window.UI.plantName(req.requesterPlant);
        return [p.manufacturer, p.mfrPartNo, p.baseUom ? 'UoM ' + p.baseUom : ''].filter(Boolean).join(' · ') || '—';
    }

    // read-only list of the batch items (data zone)
    function bulkItemsCard(req) {
        const rows = (req.items || []).map((it, i) => {
            let status;
            if (it.status === 'Declined') status = `<span class="status-pill declined">Declined</span>` +
                (it.declineComment ? `<div class="muted" style="font-size:11.5px;margin-top:3px">“${esc(it.declineComment)}”</div>` : '');
            else if (req.status === 'Completed') status = `<span class="status-pill completed">Completed</span>` +
                (it.sapId ? `<div class="muted" style="font-size:11.5px;margin-top:3px">SAP ID ${esc(it.sapId)}</div>` : '');
            else status = `<span class="status-pill in-review">In review</span>`;
            const vc = it.payload.valuationClass ? `<div class="muted" style="font-size:11.5px;margin-top:2px">Valuation ${esc(it.payload.valuationClass)}${it.payload.poUnit ? ' · PO unit ' + esc(it.payload.poUnit) : ''}</div>`
                : (it.payload.poUnit ? `<div class="muted" style="font-size:11.5px;margin-top:2px">PO unit ${esc(it.payload.poUnit)}</div>` : '');
            const mg = req.type === 'category' && it.payload.materialGroup ? `<div class="muted" style="font-size:11.5px;margin-top:2px">Material group ${esc(it.payload.materialGroup)}</div>` : '';
            return `<tr>
                <td class="muted">${i + 1}</td>
                <td style="font-weight:600;max-width:250px">${esc(bulkItemName(req, it))}
                    ${it.desc ? `<div class="muted" style="font-size:11.5px;font-weight:400;margin-top:2px">${esc(it.desc)}</div>` : ''}</td>
                <td class="muted" style="font-size:12.5px">${esc(bulkItemSub(req, it))}${vc}${mg}</td>
                <td>${status}</td>
            </tr>`;
        }).join('');
        return `<div class="panel-card"><div class="pc-title">Batch items (${(req.items || []).length})</div>
            <div class="cat-attr-wrap"><table class="data-table">
                <thead><tr><th style="width:34px">#</th><th>Item</th><th>Details</th><th style="width:150px">Status</th></tr></thead>
                <tbody>${rows}</tbody>
            </table></div></div>`;
    }

    // approver panel: approve all / approve selection (rest declined) / decline all
    function renderBulkReview(root, req, stage, zone) {
        const ds = window.Store.get().datasets;
        const active = window.Workflow.bulkActiveItems(req);
        const needVal = stage.key === 'finance';
        const needPo = stage.key === 'mdm' && req.type === 'create';
        const needMg = stage.key === 'central' && req.type === 'category';
        const isReqApproval = stage.key === 'requester_approval';
        const inputField = needVal ? 'valuationClass' : (needPo ? 'poUnit' : (needMg ? 'materialGroup' : null));
        const inputLabel = needVal ? 'Valuation class' : (needPo ? 'PO unit' : (needMg ? 'Material group' : ''));
        const options = needVal ? ds.VALUATION_CLASSES.map(v => ({ v: v.code, l: v.code + ' — ' + v.desc }))
            : (needPo ? ds.UOM.map(u => ({ v: u, l: u }))
            : (needMg ? ds.MATERIAL_GROUPS.map(g => ({ v: g.code, l: g.code + ' — ' + g.desc })) : null));

        const rowHtml = (it) => {
            let inputCell = '';
            if (options) {
                const cur = it.payload[inputField] || '';
                inputCell = `<td><select class="form-select no-ss bulk-pi" data-key="${it.key}">
                    <option value="">Select…</option>
                    ${options.map(o => `<option value="${esc(o.v)}" ${cur === o.v ? 'selected' : ''}>${esc(o.l)}</option>`).join('')}
                </select></td>`;
            } else if (isReqApproval) {
                const vc = it.payload.valuationClass;
                inputCell = `<td style="font-weight:600">${esc(vc ? vc + ' — ' + window.UI.valuationDesc(vc) : '—')}</td>`;
            }
            return `<tr>
                <td><input type="checkbox" class="bulk-sel" data-key="${it.key}" checked></td>
                <td style="font-weight:600;max-width:250px">${esc(bulkItemName(req, it))}
                    ${it.desc ? `<div class="muted" style="font-size:11.5px;font-weight:400;margin-top:2px">${esc(it.desc)}</div>` : ''}</td>
                <td class="muted" style="font-size:12.5px">${esc(bulkItemSub(req, it))}</td>
                ${inputCell}
            </tr>`;
        };
        const declinedEarlier = (req.items || []).filter(it => it.status === 'Declined').length;
        const inputHead = options ? `<th style="width:230px">${esc(inputLabel)} <span class="req">*</span></th>`
            : (isReqApproval ? '<th style="width:230px">Valuation class (set by Accounting)</th>' : '');

        zone.innerHTML = `
            <div class="result-block">
                <div class="rb-title" style="margin-bottom:4px">Your review — ${esc(stage.label)} (${esc(stage.role)}) · bulk request</div>
                <div class="muted" style="margin-bottom:12px">Approve everything, approve a selection (unselected items are <strong>declined</strong>), or decline all.
                    A comment is <strong>mandatory</strong> whenever any item is declined.${options ? ' ' + esc(inputLabel) + ' is mandatory for every approved item.' : ''}</div>
                <div class="cat-attr-wrap"><table class="data-table bulk-review-table">
                    <thead><tr>
                        <th style="width:30px"><input type="checkbox" id="bulk-sel-all" checked title="Select all"></th>
                        <th>Item</th><th>Details</th>${inputHead}
                    </tr></thead>
                    <tbody>${active.map(rowHtml).join('')}</tbody>
                </table></div>
                ${declinedEarlier ? `<div class="muted" style="margin-top:8px;font-size:12.5px">${declinedEarlier} item(s) were already declined at an earlier stage.</div>` : ''}
                <div class="field" style="margin:14px 0">
                    <label>Comment <span class="muted" style="font-weight:400">(mandatory when declining)</span></label>
                    <textarea class="form-textarea" id="review-comment" placeholder="Add a note…"></textarea>
                </div>
                <div class="form-actions">
                    <button class="btn btn-green" data-act="bulk-approve">Approve selected (<span id="bulk-count">${active.length}</span> of ${active.length})</button>
                    <button class="btn btn-danger-outline" data-act="bulk-decline-all">Decline all</button>
                </div>
            </div>`;

        const countEl = zone.querySelector('#bulk-count');
        const refreshCount = () => { countEl.textContent = zone.querySelectorAll('.bulk-sel:checked').length; };
        zone.querySelector('#bulk-sel-all').addEventListener('change', (e) => {
            zone.querySelectorAll('.bulk-sel').forEach(c => { c.checked = e.target.checked; });
            refreshCount();
        });
        zone.addEventListener('change', (e) => { if (e.target.classList.contains('bulk-sel')) refreshCount(); });

        const commentEl = () => zone.querySelector('#review-comment');
        const needComment = () => {
            const el = commentEl();
            el.classList.add('error'); el.focus();
            window.UI.toast({ title: 'Comment required', body: 'A comment is mandatory when declining items.', kind: 'danger' });
        };
        window.UI.bindActions(zone, {
            'bulk-approve': () => {
                const keys = [...zone.querySelectorAll('.bulk-sel:checked')].map(c => c.getAttribute('data-key'));
                if (!keys.length) { window.UI.toast({ title: 'Nothing selected', body: 'Select at least one item to approve — or use “Decline all”.', kind: 'danger' }); return; }
                const comment = (commentEl() || {}).value || '';
                if (keys.length < active.length && !comment.trim()) { needComment(); return; }
                let perItem = {};
                if (options) {
                    let missing = 0;
                    keys.forEach(k => {
                        const sel = zone.querySelector(`.bulk-pi[data-key="${k}"]`);
                        sel.classList.remove('error');
                        if (!sel.value) { sel.classList.add('error'); missing += 1; }
                        else perItem[k] = { [inputField]: sel.value };
                    });
                    if (missing) { window.UI.toast({ title: 'Cannot approve', body: inputLabel + ' is required for every approved item.', kind: 'danger' }); return; }
                }
                window.Workflow.actBulk(req, { approveKeys: keys, comment, perItem });
                const declined = active.length - keys.length;
                window.UI.toast({ title: 'Batch processed', body: keys.length + ' item(s) approved' + (declined ? ', ' + declined + ' declined' : '') + '.', kind: 'info' });
                window.Views.requestDetail(req.id);
            },
            'bulk-decline-all': () => {
                const comment = (commentEl() || {}).value || '';
                if (!comment.trim()) { needComment(); return; }
                window.Workflow.actBulk(req, { approveKeys: [], comment });
                window.UI.toast({ title: 'Batch declined', body: 'All ' + active.length + ' item(s) declined.', kind: 'info' });
                window.Views.requestDetail(req.id);
            }
        });
    }

    /* ---------------- Central team: new-category review ---------------- */
    function renderCategoryReview(root, req, zone) {
        const F = window.UI.field;
        const groupOptions = window.UI.ds().MATERIAL_GROUPS.map(g => ({ value: g.code, label: g.code + ' — ' + g.desc }));
        zone.innerHTML = `
            <div class="result-block">
                <div class="rb-title" style="margin-bottom:4px">Your review — Steward review (Central team)</div>
                <div class="muted" style="margin-bottom:14px">Review the proposed category. You may adjust the UNSPSC code, the category name and the attributes before approving. Assign the SAP material group this category maps to — it is mandatory. On approval the category and its attributes are added to the category catalogue.</div>
                <div id="cat-review-editor">${window.UI.categoryEditorHtml(req.payload)}</div>
                <div style="max-width:460px;margin-top:16px">
                    ${F({ label: 'Material group', name: 'cat::materialGroup', type: 'select', required: true,
                          value: req.payload.materialGroup || '', options: groupOptions,
                          placeholder: 'Select material group…', hint: 'SAP material group this category maps to' })}
                </div>
                <div class="field" style="margin:8px 0 14px">
                    <label>Comment</label>
                    <textarea class="form-textarea" id="review-comment" placeholder="Add a note…"></textarea>
                </div>
                <div class="form-actions">
                    <button class="btn btn-green" data-act="approve">Approve & add to catalog</button>
                    <button class="btn btn-danger-outline" data-act="decline">Decline</button>
                </div>
            </div>`;
        const ed = zone.querySelector('#cat-review-editor');
        window.UI.bindCategoryEditor(ed);
        window.UI.bindActions(zone, {
            'approve': () => {
                const data = window.UI.collectCategoryEditor(ed);
                if (!window.UI.validateCategoryEditor(ed, data)) { window.UI.toast({ title: 'Cannot approve', body: 'Please complete the category details.', kind: 'danger' }); return; }
                // material group is mandatory — the catalog entry must map to one
                const mg = zone.querySelector('[name="cat::materialGroup"]');
                data.materialGroup = mg ? mg.value : '';
                if (!data.materialGroup) {
                    if (mg) {
                        mg.classList.add('error');
                        const w = mg.closest('.search-select');
                        const t = w && w.querySelector('.ss-toggle');
                        if (t) t.classList.add('error');
                    }
                    const err = zone.querySelector('[data-err="cat::materialGroup"]');
                    if (err) err.textContent = 'Material group is required.';
                    window.UI.toast({ title: 'Cannot approve', body: 'Please select the material group for this category.', kind: 'danger' });
                    return;
                }
                const comment = (zone.querySelector('#review-comment') || {}).value || '';
                window.Workflow.act(req, 'approve', { comment, edits: data });
                window.UI.toast({ title: 'Category added to the catalog', body: `“${data.categoryName}” (UNSPSC ${data.unspsc}) is now available.`, kind: 'info' });
                window.Views.requestDetail(req.id);
            },
            'decline': () => doDecline(req, zone, 'decline')
        });
    }

    function collectInventory(zone) {
        const inv = {};
        zone.querySelectorAll('#inv-form [name^="inv::"]').forEach(el => { inv[el.getAttribute('name').slice(5)] = el.value.trim(); });
        return inv;
    }

    // mandatory: ABC Code, MRP Type, MRP Controller min & max, Lot-size.
    // conditional: Z1+R → reorder point, fixed lot size, safety stock; VB+N and VB+G → reorder point.
    function validateInventory(inv) {
        const errors = [];
        const req = (k, label) => { if (!inv[k] || String(inv[k]).trim() === '') errors.push({ field: k, msg: (label || k) + ' is required.' }); };
        req('abcCode', 'ABC Code');
        req('mrpType', 'MRP Type');
        // ND + EX → Min/Max levels are not applicable (disabled in the form)
        if (!(inv.mrpType === 'ND' && inv.lotSize === 'EX')) {
            req('mrpControllerMin', 'MRP Controller — Min qty');
            req('mrpControllerMax', 'MRP Controller — Max qty');
        }
        req('lotSize', 'Lot-size');
        const z1r = inv.mrpType === 'Z1' && inv.abcCode === 'R';
        const vbn = inv.mrpType === 'VB' && inv.abcCode === 'N';
        const vbg = inv.mrpType === 'VB' && inv.abcCode === 'G';
        if (z1r || vbn || vbg) req('reorderPoint', 'Reorder point');
        if (z1r) { req('fixedLotSize', 'Fixed lot size'); req('safetyStock', 'Safety Stock'); }
        return { ok: errors.length === 0, errors };
    }

    window.Views.requestDetail = function (id) {
        const req = window.Store.requestById(id);
        const root = document.getElementById('view');
        if (!req) { root.innerHTML = `<div class="page-narrow"><div class="empty-state">Request not found.</div></div>`; return; }

        const s = window.Store.session();
        const stage = window.Workflow.currentStage(req);
        const awaitingMe = window.Workflow.isAwaiting(req, s.currentRole);
        const isMyRequest = req.requesterUser === s.currentUser && s.currentRole === 'Requester';
        const statusCls = req.status === 'Completed' ? 'completed' : (req.status === 'Approved' ? 'approved' : (req.status === 'Declined' ? 'declined' : (req.status === 'Draft' ? 'draft' : 'in-review')));

        const feedback = (req.aiFeedback && req.aiFeedback.length)
            ? `<div class="banner warn"><span class="banner-icon">✦</span><div class="banner-body">
                <div class="banner-title">AI feedback captured at submission</div>
                <ul style="margin:6px 0 0 18px">${req.aiFeedback.map(w => `<li>${esc(w.msg)}</li>`).join('')}</ul></div></div>` : '';

        const p = req.payload;
        const noImg = `<svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="#C9CCC6" stroke-width="1.5"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/></svg>`;
        const stageNow = req.status === 'Draft' ? 'Not submitted'
            : (req.status === 'Declined' ? 'Returned to requester'
            : (req.status === 'Completed' ? 'All steps completed'
            : (stage ? stage.label + ' — ' + stage.role : '—')));

        root.innerHTML = `
            <div class="sub-header"><span class="crumb-link" data-act="home">Material Master</span> ›
                <span class="crumb-link" data-act="back">Requests</span> › ${esc(window.Workflow.reqNo(req))}</div>
            <div class="page-full">
                <div class="req-head">
                    <div>
                        <div class="req-eyebrow">${esc(window.Workflow.typeLabel(req.type))} · ${esc(window.Workflow.reqNo(req))}</div>
                        <h1 class="req-title">${esc(p.shortName || req.title)}</h1>
                    </div>
                    <div class="req-head-right">
                        <span class="status-pill ${statusCls}">${esc(req.status)}</span>
                        ${req.sapId ? `<span class="sap-chip">SAP ID ${esc(req.sapId)}</span>` : ''}
                    </div>
                </div>

                <div class="panel-card tracker-card">${window.UI.workflowTracker(req)}</div>
                ${feedback}

                <div class="req-layout">
                    <div class="req-main">
                        <div id="action-zone"></div>
                        <div id="data-zone">${req.bulk ? bulkItemsCard(req) : (req.type === 'category' ? categoryCards(p) : dataCards(p))}</div>
                    </div>
                    <aside class="req-side">
                        <div class="panel-card">
                            <div class="pc-title">Summary</div>
                            ${(req.type === 'category' || req.bulk) ? '' : `<div class="side-photo">${p.image ? `<img src="${esc(p.image)}" alt="Item photo">` : noImg}</div>`}
                            <div class="def-grid one-col">
                                ${defRow('Current stage', stageNow)}
                                ${defRow('Requester', req.requesterUser)}
                                ${defRow('Plant', req.requesterPlant + ' — ' + window.UI.plantName(req.requesterPlant))}
                                ${defRow('Created', window.UI.nowLabel(req.createdTs))}
                                ${req.sapId ? defRow('SAP ID', req.sapId) : ''}
                            </div>
                            ${req.materialId || req.sapId ? `<button class="btn btn-green-outline btn-sm" style="width:100%;margin-top:12px" data-act="view-item">View material record</button>` : ''}
                        </div>
                        <div class="panel-card">
                            <div class="pc-title">Activity</div>
                            ${window.UI.historyList(req)}
                        </div>
                    </aside>
                </div>
            </div>`;

        renderActionZone(root, req, stage, awaitingMe, isMyRequest);

        window.UI.bindActions(root, {
            'home': () => window.UI.go('#/master'),
            'back': () => window.UI.go('#/inbox'),
            'view-item': () => {
                const mid = req.materialId || (window.Store.materials().find(m => m.sapId === req.sapId) || {}).id;
                if (mid) window.UI.go('#/item/' + mid);
            }
        });
    };

    function renderActionZone(root, req, stage, awaitingMe, isMyRequest) {
        const zone = root.querySelector('#action-zone');

        // ---- bulk requests: batch banners & batch review ----
        if (req.bulk) {
            const items = req.items || [];
            const declinedN = items.filter(it => it.status === 'Declined').length;
            const doneN = items.length - declinedN;
            if (req.status === 'Declined') {
                const last = [...req.history].reverse().find(h => h.action === 'declined');
                zone.innerHTML = `<div class="banner danger"><span class="banner-icon">↩️</span><div class="banner-body">
                    <div class="banner-title">Bulk request declined — all ${items.length} item(s) were declined</div>
                    ${last && last.comment ? '“' + esc(last.comment) + '”' : ''} ${isMyRequest ? 'You can submit the items again individually from the bulk upload page.' : ''}</div></div>`;
                return;
            }
            if (req.status === 'Completed') {
                zone.innerHTML = `<div class="banner match"><span class="banner-icon">✓</span><div class="banner-body">
                    <div class="banner-title">Bulk request completed</div>
                    ${doneN} item(s) ${req.type === 'create' ? 'created in the material master' : (req.type === 'extend' ? 'extended to plant ' + esc(req.requesterPlant) : 'added to the category catalogue')}${declinedN ? ' · ' + declinedN + ' item(s) declined along the way' : ''}. Per-item results are listed below.</div></div>`;
                return;
            }
            if (!awaitingMe) {
                const st = window.Workflow.currentStage(req);
                zone.innerHTML = `<div class="banner info"><span class="banner-icon">⏳</span><div class="banner-body">
                    ${window.Workflow.bulkActiveItems(req).length} item(s) awaiting <strong>${esc(st ? st.role : '')}</strong> (${esc(st ? st.label : '')}).
                    ${window.Store.session().currentRole === 'Requester' ? 'You will be notified when it progresses.' : 'You are acting as ' + esc(window.Store.session().currentRole) + '; switch role to act on this.'}</div></div>`;
                return;
            }
            renderBulkReview(root, req, stage, zone);
            return;
        }

        // Requester view of a declined request → edit & resubmit
        if (isMyRequest && req.status === 'Declined') {
            const lastDecline = [...req.history].reverse().find(h => h.action === 'declined');
            if (req.type === 'category') {
                zone.innerHTML = `<div class="banner danger"><span class="banner-icon">↩️</span><div class="banner-body">
                        <div class="banner-title">Declined by ${esc(lastDecline ? lastDecline.actorRole : 'reviewer')} — please fix and resubmit</div>
                        ${lastDecline && lastDecline.comment ? '“' + esc(lastDecline.comment) + '”' : 'Please review and resubmit.'}</div></div>
                    <div class="result-block" style="margin-top:14px">
                        <div class="rb-title" style="margin-bottom:10px">Fix your category proposal</div>
                        <div id="cat-fix-editor">${window.UI.categoryEditorHtml(req.payload)}</div>
                        <div class="form-actions" style="margin-top:16px"><button class="btn btn-green" data-act="resubmit-cat">Resubmit request</button></div>
                    </div>`;
                const ed = zone.querySelector('#cat-fix-editor');
                window.UI.bindCategoryEditor(ed);
                window.UI.bindActions(zone, {
                    'resubmit-cat': () => {
                        const data = window.UI.collectCategoryEditor(ed);
                        if (!window.UI.validateCategoryEditor(ed, data)) { window.UI.toast({ title: 'Cannot resubmit', body: 'Please complete the category details.', kind: 'danger' }); return; }
                        window.Workflow.resubmit(req, Object.assign({ name: data.categoryName, shortName: data.categoryName }, data));
                        window.UI.toast({ title: 'Resubmitted', body: 'Your category proposal is back with the Central team.' });
                        window.Views.requestDetail(req.id);
                    }
                });
                return;
            }
            zone.innerHTML = `<div class="banner danger"><span class="banner-icon">↩️</span><div class="banner-body">
                    <div class="banner-title">Declined by ${esc(lastDecline ? lastDecline.actorRole : 'reviewer')} — please fix and resubmit</div>
                    ${lastDecline && lastDecline.comment ? '“' + esc(lastDecline.comment) + '”' : 'Please review and resubmit.'}</div>
                <div class="banner-actions">
                    ${req.type === 'create' || req.type === 'amend' ? `<button class="btn btn-green btn-sm" data-act="edit-resubmit">Edit & resubmit</button>` : `<button class="btn btn-green btn-sm" data-act="resubmit">Resubmit</button>`}
                </div></div>`;
            window.UI.bindActions(zone, {
                'edit-resubmit': () => {
                    window.Views._draft = { type: req.type, payload: req.payload, materialId: req.materialId,
                        resubmitId: req.id, analysis: { known: true } };
                    window.UI.go('#/request/new?type=' + req.type);
                },
                'resubmit': () => { window.Workflow.resubmit(req); window.UI.toast({ title: 'Resubmitted', body: 'Back in review.' }); window.Views.requestDetail(req.id); }
            });
            return;
        }

        // Draft owned by requester
        if (isMyRequest && req.status === 'Draft') {
            zone.innerHTML = `<div class="banner info"><span class="banner-icon">📝</span><div class="banner-body">This request is a draft.</div>
                <div class="banner-actions">
                    <button class="btn btn-green btn-sm" data-act="edit-draft">Continue editing</button>
                    <button class="btn btn-danger-outline btn-sm" data-act="delete-draft">Delete draft</button>
                </div></div>`;
            window.UI.bindActions(zone, {
                'edit-draft': () => {
                    window.Views._draft = { type: req.type, payload: req.payload, materialId: req.materialId, resubmitId: req.id, analysis: { known: true } };
                    window.UI.go('#/request/new?type=' + req.type);
                },
                'delete-draft': () => confirmDeleteDraft(req, () => window.UI.go('#/inbox'))
            });
            return;
        }

        if (req.status === 'Completed') {
            if (req.type === 'category') {
                const p = req.payload;
                const central = window.Store.session().currentRole === 'Central team';
                zone.innerHTML = `<div class="banner match"><span class="banner-icon">✓</span><div class="banner-body">
                    <div class="banner-title">Category added to the catalog</div>“${esc(p.categoryName)}” (UNSPSC ${esc(p.unspsc)}) with ${(p.catAttributes || []).length} attributes is now available for item classification.</div>
                    ${central ? `<div class="banner-actions"><button class="btn btn-green-outline btn-sm" data-act="view-catalog">View category catalogue</button></div>` : ''}</div>`;
                window.UI.bindActions(zone, { 'view-catalog': () => window.UI.go('#/categories') });
                return;
            }
            zone.innerHTML = `<div class="banner match"><span class="banner-icon">✓</span><div class="banner-body">
                <div class="banner-title">Completed</div>SAP responded with ID <strong>${esc(req.sapId)}</strong>. The material record has been ${verb(req.type)}.</div>
                ${req.materialId || true ? `<div class="banner-actions"><button class="btn btn-green-outline btn-sm" data-act="view-item">View record</button></div>` : ''}</div>`;
            window.UI.bindActions(zone, { 'view-item': () => {
                const mid = req.materialId || (window.Store.materials().find(m => m.sapId === req.sapId) || {}).id;
                if (mid) window.UI.go('#/item/' + mid);
            }});
            return;
        }

        if (!awaitingMe) {
            const st = window.Workflow.currentStage(req);
            // SAP done, item approved & live — only the Inventory task remains open
            if (req.status === 'Approved') {
                zone.innerHTML = `<div class="banner match"><span class="banner-icon">✓</span><div class="banner-body">
                    <div class="banner-title">Item approved</div>SAP responded with ID <strong>${esc(req.sapId)}</strong> — the record is live in the material master.
                    Inventory setup by the <strong>Inventory team</strong> is still pending, but does not hold the item.</div>
                    <div class="banner-actions"><button class="btn btn-green-outline btn-sm" data-act="view-item">View record</button></div></div>`;
                window.UI.bindActions(zone, { 'view-item': () => {
                    const mid = req.materialId || (window.Store.materials().find(m => m.sapId === req.sapId) || {}).id;
                    if (mid) window.UI.go('#/item/' + mid);
                }});
                return;
            }
            zone.innerHTML = `<div class="banner info"><span class="banner-icon">⏳</span><div class="banner-body">
                Awaiting <strong>${esc(st ? st.role : '')}</strong> (${esc(st ? st.label : '')}). ${window.Store.session().currentRole === 'Requester' ? 'You will be notified when it progresses.' : 'You are acting as ' + esc(window.Store.session().currentRole) + '; switch role to act on this.'}</div></div>`;
            return;
        }

        // ---- Inventory team: post-SAP inventory setup form ----
        if (stage.key === 'inventory') { renderInventoryPanel(root, req, zone); return; }

        // ---- Central team: new-category review (editable proposal) ----
        if (req.type === 'category' && stage.key === 'central') { renderCategoryReview(root, req, zone); return; }

        // ---- awaiting the current role: render the action panel ----
        const ds = window.Store.get().datasets;
        let extra = '';
        if (stage.key === 'finance') {
            // a request bounced back by the requester carries their decline note — surface it
            const lastNo = [...(req.history || [])].reverse().find(h => h.action === 'declined');
            const bounced = lastNo && /returned to (Finance|Accounting)/.test(lastNo.text || '');
            extra = `${bounced ? `<div class="banner warn mb-0" style="margin-bottom:12px"><span class="banner-icon">↩️</span><div class="banner-body">
                <div class="banner-title">Declined by ${esc(lastNo.actorUser)} (Requester)</div>“${esc(lastNo.comment || '')}” — please select the valuation class again.</div></div>` : ''}
                <div class="field" style="max-width:420px;margin-bottom:14px">
                <label>Valuation Class <span class="req">*</span></label>
                <select class="form-select" id="valclass">
                    <option value="">Select valuation class…</option>
                    ${ds.VALUATION_CLASSES.map(v => `<option value="${v.code}" ${req.payload.valuationClass === v.code ? 'selected' : ''}>${v.code} — ${esc(v.desc)}</option>`).join('')}
                </select>
                <div class="field-error" id="valclass-err"></div></div>`;
        }
        if (stage.key === 'requester_approval') {
            const vc = req.payload.valuationClass;
            extra = `<div class="banner info mb-0" style="margin-bottom:12px"><span class="banner-icon">💰</span><div class="banner-body">
                <div class="banner-title">Accounting selected valuation class ${esc(vc ? vc + ' — ' + window.UI.valuationDesc(vc) : '—')}</div>
                Approve to send the request to Technical review, or decline with a note (mandatory) to return it to Accounting.</div></div>`;
        }
        if (stage.key === 'mdm' && (req.type === 'create' || req.type === 'amend')) {
            extra = `<div class="banner info mb-0" style="margin-bottom:12px"><span class="banner-icon">✎</span><div class="banner-body">You may edit any field below before approving.</div></div>
                ${editableGrid(req.payload)}`;
        }
        // extend: MDM only accepts or declines — no item fields to edit
        if (stage.key === 'mdm' && req.type === 'extend') {
            const m = req.materialId ? window.Store.materialById(req.materialId) : null;
            const from = (m && m.plants && m.plants.length) ? m.plants.map(pc => window.UI.plantLabel(pc)).join(', ') : '—';
            extra = `<div class="banner info mb-0" style="margin-bottom:12px"><span class="banner-icon">↗</span><div class="banner-body">
                <div class="banner-title">Plant extension request</div>
                ${esc(req.requesterUser)} requests extending this item to plant <strong>${esc(window.UI.plantLabel(req.requesterPlant))}</strong>.
                Currently in: ${esc(from)}. Approve to update SAP, or decline with a note.</div></div>`;
        }

        // Accounting only supplies the valuation class — it cannot decline
        const canDecline = stage.key !== 'finance';
        zone.innerHTML = `
            <div class="result-block">
                <div class="rb-title" style="margin-bottom:10px">Your review — ${esc(stage.label)} (${esc(stage.role)})</div>
                ${extra}
                <div class="field" style="margin-bottom:14px">
                    <label>Comment</label>
                    <textarea class="form-textarea" id="review-comment" placeholder="Add a note…"></textarea>
                </div>
                <div class="form-actions">
                    <button class="btn btn-green" data-act="approve">${stage.key === 'finance' ? 'Submit' : 'Approve'}</button>
                    ${canDecline ? '<button class="btn btn-danger-outline" data-act="decline">Decline</button>' : ''}
                </div>
            </div>`;

        window.UI.bindActions(zone, {
            'approve': () => {
                const comment = (zone.querySelector('#review-comment') || {}).value || '';
                const data = { comment };
                if (stage.key === 'finance') {
                    const vc = zone.querySelector('#valclass').value;
                    if (!vc) { zone.querySelector('#valclass-err').textContent = 'Valuation class is required.'; zone.querySelector('#valclass').classList.add('error'); return; }
                    data.valuationClass = vc;
                }
                if (stage.key === 'mdm' && (req.type === 'create' || req.type === 'amend')) {
                    data.edits = collectEdits(root);
                    // PO unit is assigned by MDM and mandatory before approving
                    if (!data.edits.poUnit) {
                        const native = root.querySelector('#mdm-edit [name="poUnit"]');
                        if (native) {
                            native.classList.add('error');
                            const w = native.closest('.search-select');
                            const t = w && w.querySelector('.ss-toggle');
                            if (t) t.classList.add('error');
                        }
                        const err = root.querySelector('#mdm-edit [data-err="poUnit"]');
                        if (err) err.textContent = 'PO unit is required.';
                        window.UI.toast({ title: 'Cannot approve', body: 'Please select the PO unit before approving.', kind: 'danger' });
                        return;
                    }
                }
                window.Workflow.act(req, 'approve', data);
                window.UI.toast({ title: stage.key === 'finance' ? 'Submitted' : 'Approved', body: nextMsg(req), kind: 'info' });
                window.Views.requestDetail(req.id);
            },
            'decline': () => doDecline(req, zone, 'decline')
        });
    }

    // shared draft-delete confirmation (also used by the inbox)
    function confirmDeleteDraft(req, after) {
        window.UI.openModal({
            title: 'Delete draft',
            bodyHtml: `<p>Delete draft <strong>${esc(req.payload && req.payload.shortName || req.title)}</strong> (${esc(window.Workflow.reqNo(req))})?<br>
                <span class="muted">This cannot be undone.</span></p>`,
            buttons: [
                { label: 'Cancel', cls: 'btn-outline', onClick: (o) => o.remove() },
                { label: 'Delete draft', cls: 'btn-danger-outline', onClick: (o) => {
                    o.remove();
                    if (window.Workflow.deleteDraft(req.id)) {
                        window.UI.toast({ title: 'Draft deleted', body: req.payload && req.payload.shortName || req.title, kind: 'danger' });
                        if (after) after();
                    }
                } }
            ]
        });
    }
    window.Views.confirmDeleteDraft = confirmDeleteDraft;

    function doDecline(req, zone, action) {
        const comment = (zone.querySelector('#review-comment') || {}).value || '';
        if (!comment.trim()) {
            window.UI.toast({ title: 'Comment required', body: 'A comment is mandatory to ' + (action === 'correction' ? 'send back' : 'decline') + '.', kind: 'danger' });
            const ta = zone.querySelector('#review-comment'); if (ta) { ta.classList.add('error'); ta.focus(); }
            return;
        }
        // the requester declining the valuation class returns it to Accounting, not to themselves
        const st = window.Workflow.currentStage(req);
        const toAccounting = st && st.key === 'requester_approval';
        window.Workflow.act(req, action, { comment });
        window.UI.toast({ title: action === 'correction' ? 'Sent for correction' : 'Declined',
            body: toAccounting ? 'Returned to Accounting with your note.' : 'Returned to the requester.', kind: 'info' });
        window.Views.requestDetail(req.id);
    }

    function nextMsg(req) {
        if (req.status === 'Completed') return 'Request completed — SAP ID ' + req.sapId + '.';
        const st = window.Workflow.currentStage(req);
        return st ? 'Forwarded to ' + st.role + '.' : 'Advanced.';
    }
    function verb(type) {
        return { create: 'created', amend: 'updated', extend: 'extended to your plant', block: 'blocked at plant level',
            reactivate: 'reactivated', block_proc: 'blocked for procurement', block_total: 'totally blocked', unblock_central: 'unblocked',
            valuation: 'updated (valuation class)' }[type] || 'processed';
    }
})();
