/* ============================================================
   views/request-form.js — create / amend form + extend/block/reactivate confirm
   ============================================================ */
(function () {
    window.Views = window.Views || {};
    const esc = (s) => window.UI.esc(s);
    const F = window.UI.field;

    function ds() { return window.Store.get().datasets; }
    function groupOptions() { return ds().MATERIAL_GROUPS.map(g => ({ value: g.code, label: g.code + ' — ' + g.desc })); }
    function plantOptions() { return ds().PLANTS.map(p => ({ value: p.code, label: p.code + ' — ' + p.name })); }
    function storageFieldHtml(plant, value) {
        if (!plant) return F({ label: 'Storage location', name: 'storageLocation', type: 'select', value: '',
                   options: [], required: true, disabled: true, placeholder: 'Select a plant first',
                   hint: 'Storage locations load from the selected plant' });
        return F({ label: 'Storage location', name: 'storageLocation', type: 'select', value,
                   options: window.UI.storageOptionsFor(plant), required: true,
                   hint: 'Locations of the selected plant' });
    }

    /* ---------------- entry ---------------- */
    window.Views.requestForm = function (query) {
        const draft = window.Views._draft;
        const type = (draft && draft.type) || (query && query.type) || 'create';
        if (type === 'extend' || type === 'block' || type === 'reactivate') return confirmView(type, draft);
        return editView(type, draft);
    };

    /* ================= CREATE / AMEND editable form ================= */
    function editView(type, draft) {
        const root = document.getElementById('view');
        let payload;
        let materialId = null;
        if (draft && draft.payload) payload = Object.assign({}, draft.payload);
        else if (draft && draft.materialId) { // amend from item
            const m = window.Store.materialById(draft.materialId);
            materialId = m.id;
            payload = payloadFromMaterial(m);
        } else payload = emptyPayload();
        if (draft && draft.materialId) materialId = draft.materialId;

        // material description defaults from group
        if (payload.materialGroup && !payload.materialDescription) payload.materialDescription = window.UI.groupDesc(payload.materialGroup);

        const aiFilled = !!(draft && draft.analysis && draft.analysis.known);
        const title = type === 'amend' ? 'Request for amending item' : 'Request for adding new item';

        const categoryOptions = (ds().CATEGORY_ATTRIBUTES || []).map(c => ({ value: c.unspsc, label: c.label + ' — UNSPSC ' + c.unspsc }));

        root.innerHTML = `
            <div class="sub-header"><span class="crumb-link" data-act="back">Material Master</span> › ${esc(title)}</div>
            <div class="page-narrow form-page">
                <div class="req-head rf-head">
                    <div>
                        <div class="req-eyebrow">${type === 'amend' ? 'Amend request' : 'New item request'}</div>
                        <h1 class="req-title">${esc(title)}</h1>
                        <div class="rf-head-sub">Fill in the item data below — the AI engine validates the mandatory fields and completes the record when you process the item.</div>
                    </div>
                    <div class="req-head-right rf-head-actions">
                        <button class="btn btn-ai-search" id="primary-btn" data-act="process">✦ Process item</button>
                        <button class="btn btn-green-outline" data-act="draft">Save as draft</button>
                        <button class="btn btn-outline" data-act="back">Cancel</button>
                    </div>
                </div>

                <div id="ai-feedback"></div>

                <form id="req-form">
                    <input type="hidden" name="name" value="${esc(payload.name)}">
                    <input type="hidden" name="unspscLabel" value="${esc(payload.unspscLabel)}">
                    <div class="form-grid">
                        <div class="rf-section"><span class="rf-step">1</span><span class="t">Item identification</span><span class="rule"></span></div>
                        ${F({ label: 'Short name', name: 'shortName', value: payload.shortName, required: true, aiFilled })}
                        ${F({ label: 'Long description', name: 'longDesc', type: 'textarea', value: payload.longDesc, required: true, aiFilled, span: 3,
                              readonly: aiFilled, hint: aiFilled ? 'Generated by the AI engine — not editable' : 'Will be generated and locked once the AI identifies the item' })}
                        <div class="field col-span-3">
                            <label>Item photo</label>
                            <input type="hidden" name="image" id="img-data" value="${esc(payload.image || '')}">
                            <div class="img-upload">
                                <div class="img-preview" id="img-preview">${payload.image ? `<img src="${esc(payload.image)}" alt="">` : '<span class="muted">No image</span>'}</div>
                                <div class="img-upload-controls">
                                    <input type="file" id="img-file" accept="image/png,image/jpeg,image/jpg,image/svg+xml,image/webp" hidden>
                                    <div style="display:flex;gap:8px;align-items:center">
                                        <button type="button" class="btn btn-outline btn-sm" data-act="choose-img">Choose image</button>
                                        <button type="button" class="btn btn-link ${payload.image ? '' : 'hidden'}" id="img-remove-btn" data-act="remove-img">Remove</button>
                                    </div>
                                    <div class="hint">PNG, JPG, SVG or WebP · max 2 MB. Shown with the item everywhere.</div>
                                </div>
                            </div>
                        </div>

                        <div class="rf-section"><span class="rf-step">2</span><span class="t">Classification</span><span class="rule"></span></div>
                        ${F({ label: 'Material Type', name: 'materialType', value: 'ROH', readonly: true, hint: 'Fixed for Demand Planning' })}
                        ${F({ label: 'Material Group', name: 'materialGroup', type: 'select', value: payload.materialGroup, options: groupOptions(), required: true, aiFilled })}
                        ${F({ label: 'Material Description', name: 'materialDescription', value: payload.materialDescription, readonly: true, hint: 'Populated from Material Group' })}
                        ${F({ label: 'Category', name: 'unspsc', type: 'select', value: payload.unspsc, options: categoryOptions, aiFilled, hint: 'Loads the attribute set below', placeholder: 'Select category…' })}
                        ${F({ label: 'UNSPSC code', name: 'unspscMirror', value: payload.unspsc, readonly: true, hint: 'From selected category' })}
                        ${F({ label: 'Material type', name: 'matTypeChoice', type: 'select', value: payload.matTypeChoice, options: ds().MATERIAL_TYPE_CHOICES, required: true, hint: 'OEM / Generic / Engineered / Commercial' })}
                        ${F({ label: 'Manufacturer name', name: 'manufacturer', value: payload.manufacturer, hint: 'Mandatory for OEM' })}
                        ${F({ label: 'Manufacturer part #', name: 'mfrPartNo', value: payload.mfrPartNo, hint: 'Mandatory for OEM' })}

                        <div class="rf-section"><span class="rf-step">3</span><span class="t">Logistics & planning</span><span class="rule"></span></div>
                        ${F({ label: 'Base unit of measure', name: 'baseUom', type: 'select', value: payload.baseUom, options: ds().UOM, required: true })}
                        <div id="storage-field" style="display:contents">${storageFieldHtml((payload.plants && payload.plants.length ? payload.plants[0] : payload.plant) || '', payload.storageLocation)}</div>
                        ${F({ label: 'MRP type', name: 'mrpType', type: 'select', value: payload.mrpType, options: ds().MRP_TYPES, required: true, hint: 'PD (planned) / ND (no planning)' })}
                        ${F({ label: 'MRP planning enabled?', name: 'mrpEnabled', type: 'radio', value: payload.mrpEnabled, options: ['Yes', 'No'], required: true })}
                        ${F({ label: 'Batch-managed?', name: 'batchManaged', type: 'radio', value: payload.batchManaged, options: ['Yes', 'No'], required: true })}
                        ${F({ label: 'Record type', name: 'recordType', type: 'radio', value: payload.recordType, options: ['Golden record', 'Sourcing record'], required: true })}
                        <div class="field col-span-3"><label>Plants<span class="req">*</span> <span class="muted" style="font-weight:400;font-size:12px">(select one or more)</span></label>
                            <input type="text" class="form-input plants-filter" id="plants-filter" placeholder="Search plants…">
                            <div class="checkbox-group plants-picker plants-picker-wide" id="plants-picker">
                                ${ds().PLANTS.map(pl => `<label class="checkbox-label"><input type="checkbox" class="rf-plant" value="${pl.code}" ${((payload.plants && payload.plants.length ? payload.plants : (payload.plant ? [payload.plant] : []))).indexOf(pl.code) !== -1 ? 'checked' : ''}> ${pl.code} — ${esc(pl.name)}</label>`).join('')}
                            </div>
                            <div class="field-error" data-err="plant"></div>
                        </div>
                    </div>

                    <div class="rf-section" style="margin-top:28px"><span class="rf-step">4</span><span class="t">Technical attributes</span><span class="note">defined by the selected category${aiFilled ? ' · values prefilled by AI' : ''}</span><span class="rule"></span></div>
                    <div class="form-grid" id="attr-zone">${attrZoneInner(payload.unspsc, payload.attributes)}</div>
                </form>
            </div>`;

        // image upload
        const fileInput = root.querySelector('#img-file');
        if (fileInput) fileInput.addEventListener('change', e => {
            const f = e.target.files && e.target.files[0];
            if (!f) return;
            if (f.size > 2 * 1024 * 1024) { window.UI.toast({ title: 'Image too large', body: 'Please choose an image under 2 MB.', kind: 'danger' }); e.target.value = ''; return; }
            const reader = new FileReader();
            reader.onload = () => setFormImage(root, reader.result);
            reader.readAsDataURL(f);
        });

        // plants picker: filter the checkbox list (checked plants always stay visible)
        const plantsFilter = root.querySelector('#plants-filter');
        if (plantsFilter) plantsFilter.addEventListener('input', () => {
            const q = plantsFilter.value.trim().toLowerCase();
            root.querySelectorAll('#plants-picker .checkbox-label').forEach(lb => {
                const keep = !q || lb.textContent.toLowerCase().indexOf(q) !== -1 || lb.querySelector('input').checked;
                lb.style.display = keep ? '' : 'none';
            });
        });

        // live: first selected plant → storage-location options (keep value if still valid)
        const plantsPicker = root.querySelector('#plants-picker');
        if (plantsPicker) plantsPicker.addEventListener('change', e => {
            if (!e.target.classList || !e.target.classList.contains('rf-plant')) return;
            const first = root.querySelector('.rf-plant:checked');
            const sel = root.querySelector('[name="storageLocation"]');
            const holder = root.querySelector('#storage-field');
            if (holder) holder.innerHTML = storageFieldHtml(first ? first.value : '', sel ? sel.value : '');
        });

        // live: material group → description
        root.querySelector('[name="materialGroup"]').addEventListener('change', e => {
            root.querySelector('[name="materialDescription"]').value = window.UI.groupDesc(e.target.value);
        });
        // live: category → UNSPSC mirror + attribute set (preserving any shared values)
        root.querySelector('[name="unspsc"]').addEventListener('change', e => {
            const unspsc = e.target.value;
            const mirror = root.querySelector('[name="unspscMirror"]'); if (mirror) mirror.value = unspsc;
            const labelInput = root.querySelector('[name="unspscLabel"]');
            const schema = window.UI.categorySchema(unspsc);
            if (labelInput) labelInput.value = schema ? schema.label : '';
            const current = readAttrInputs(root);
            root.querySelector('#attr-zone').innerHTML = attrZoneInner(unspsc, current);
        });

        window.UI.bindActions(root, {
            'back': () => history.length > 1 ? history.back() : window.UI.go('#/master'),
            'process': () => doProcess(type, materialId, draft),
            'submit': () => doSubmit(type, materialId, draft),
            'choose-img': () => { const fi = root.querySelector('#img-file'); if (fi) fi.click(); },
            'remove-img': () => setFormImage(root, ''),
            'draft': () => { const p = collect(); const dr = window.Workflow.createRequest({ type, payload: p, materialId, draft: true, aiFeedback: [] });
                window.UI.toast({ title: 'Saved as draft', body: 'Find it in your Inbox → Drafts.' });
                if (draft && draft.fromBulk) { window.Views.bulkMarkAction(draft.fromBulk.batch, draft.fromBulk.i, 'Draft saved — ' + window.Workflow.reqNo(dr)); window.UI.go('#/bulk/' + draft.fromBulk.batch); return; }
                window.UI.go('#/inbox'); }
        });
    }

    /* ---- typed attribute controls driven by the category schema ----
       attribute: { name, fieldType(Text|Number|Range|Yes/No|List|Date), uom, mandatory, options } */
    function listOptions(a, current) {
        const opts = String(a.options || '').split(',').map(x => x.trim()).filter(Boolean);
        if (current && opts.indexOf(current) === -1) opts.unshift(current);
        return opts;
    }
    function numPart(v) { const n = parseFloat(String(v === undefined || v === null ? '' : v).replace(',', '.')); return isNaN(n) ? '' : n; }

    function attrField(a, val) {
        const name = 'attr::' + a.name;
        const t = a.fieldType || 'Text';
        const label = `${esc(a.name)}${a.uom ? ` <span class="attr-uom">(${esc(a.uom.toLowerCase())})</span>` : ''}${a.mandatory ? '<span class="req">*</span>' : ''}`;
        let control;
        if (t === 'Number') {
            control = `<input class="form-input ai-filled" type="number" step="any" name="${name}" value="${esc(numPart(val))}">`;
        } else if (t === 'Range') {
            const parts = String(val || '').split(/–|—|\.\.|to/i);
            control = `<div class="range-pair">
                <input class="form-input ai-filled" type="number" step="any" name="${name}" placeholder="Min" value="${esc(numPart(parts[0]))}">
                <span class="muted">–</span>
                <input class="form-input ai-filled" type="number" step="any" name="${name}::max" placeholder="Max" value="${esc(numPart(parts[1]))}">
            </div>`;
        } else if (t === 'Yes/No') {
            control = `<select class="form-select ai-filled" name="${name}">
                <option value="">Select…</option>
                <option ${val === 'Yes' ? 'selected' : ''}>Yes</option>
                <option ${val === 'No' ? 'selected' : ''}>No</option></select>`;
        } else if (t === 'List') {
            control = `<select class="form-select ai-filled" name="${name}">
                <option value="">Select…</option>
                ${listOptions(a, String(val || '').trim()).map(o => `<option value="${esc(o)}" ${String(val || '').trim() === o ? 'selected' : ''}>${esc(o)}</option>`).join('')}</select>`;
        } else if (t === 'Date') {
            control = `<input class="form-input ai-filled" type="date" name="${name}" value="${esc(val || '')}">`;
        } else {
            control = `<input class="form-input ai-filled" type="text" name="${name}" value="${esc(val || '')}">`;
        }
        return `<div class="field"><label>${label}</label>${control}<div class="field-error" data-err="${name}"></div></div>`;
    }

    // strip a trailing uom from an AI-prefilled value so typed controls can use it
    function attrValueFor(a, values) {
        let v = values[a.name];
        if (v === undefined || v === null) return '';
        v = String(v).trim();
        if (a.uom && new RegExp('\\s*' + a.uom + '\\s*$', 'i').test(v)) v = v.replace(new RegExp('\\s*' + a.uom + '\\s*$', 'i'), '');
        return v;
    }

    // render attribute inputs for the category's schema (or a hint when none)
    function attrZoneInner(unspsc, values) {
        values = values || {};
        const schema = window.UI.categorySchema(unspsc);
        if (schema) {
            return schema.attributes.map(a => attrField(a, attrValueFor(a, values))).join('');
        }
        const extra = Object.keys(values).length
            ? Object.entries(values).map(([k, v]) => F({ label: k, name: 'attr::' + k, value: v, aiFilled: true })).join('')
            : '';
        return `<div class="field col-span-3"><div class="banner info mb-0"><span class="banner-icon">ℹ️</span>
            <div class="banner-body">No predefined attribute set for this category yet. Select a <strong>Category</strong> above to load its attributes${extra ? ', or edit the detected ones below' : ''}. Manage categories &amp; attributes from the <strong>Category catalog</strong>.</div></div></div>${extra}`;
    }
    // set/clear the uploaded item image + preview
    function setFormImage(root, dataUrl) {
        const hidden = root.querySelector('#img-data'); if (hidden) hidden.value = dataUrl || '';
        const prev = root.querySelector('#img-preview');
        if (prev) prev.innerHTML = dataUrl ? `<img src="${dataUrl}" alt="">` : '<span class="muted">No image</span>';
        const rm = root.querySelector('#img-remove-btn'); if (rm) rm.classList.toggle('hidden', !dataUrl);
    }
    // read current attr:: inputs into a values map (range max halves are skipped)
    function readAttrInputs(root) {
        const vals = {};
        root.querySelectorAll('#attr-zone [name^="attr::"]').forEach(el => {
            const n = el.getAttribute('name');
            if (n.indexOf('::max') !== -1) return;
            vals[n.slice(6)] = el.value;
        });
        return vals;
    }

    function collect() {
        const form = document.getElementById('req-form');
        const fd = new FormData(form);
        const p = {};
        for (const [k, v] of fd.entries()) p[k] = v;
        const unspsc = p.unspsc || '';
        const schema = window.UI.categorySchema(unspsc);
        // attributes: schema-aware (typed values, uom appended, ranges combined)
        const attrs = {};
        if (schema) {
            schema.attributes.forEach(a => {
                const t = a.fieldType || 'Text';
                let v = '';
                if (t === 'Range') {
                    const min = String(p['attr::' + a.name] || '').trim();
                    const max = String(p['attr::' + a.name + '::max'] || '').trim();
                    if (min || max) v = (min || '…') + '–' + (max || '…');
                } else {
                    v = String(p['attr::' + a.name] || '').trim();
                }
                if (v && a.uom) v += ' ' + a.uom.toLowerCase();
                if (v) attrs[a.name] = v;
            });
        } else {
            Object.keys(p).forEach(k => {
                if (k.indexOf('attr::') === 0 && k.indexOf('::max') === -1) {
                    const name = k.slice(6);
                    if (String(p[k]).trim()) attrs[name] = p[k];
                }
            });
        }
        const label = (p.unspscLabel && p.unspscLabel.trim()) || (schema ? schema.label : '');
        const shortName = p.shortName || '';
        return {
            name: (p.name && p.name.trim()) || shortName, shortName, longDesc: p.longDesc || '',
            materialType: 'ROH', matTypeChoice: p.matTypeChoice || '',
            manufacturer: p.manufacturer || '', mfrPartNo: p.mfrPartNo || '',
            unspsc, unspscLabel: label, category: label,
            materialGroup: p.materialGroup || '', materialDescription: p.materialDescription || '',
            baseUom: p.baseUom || '',
            plants: [...document.querySelectorAll('.rf-plant:checked')].map(cb => cb.value),
            plant: ([...document.querySelectorAll('.rf-plant:checked')].map(cb => cb.value))[0] || '',
            storageLocation: p.storageLocation || '',
            mrpEnabled: p.mrpEnabled || '', batchManaged: p.batchManaged || '', mrpType: p.mrpType || '',
            recordType: p.recordType || '', valuationClass: '',
            attributes: attrs, image: p.image || ''
        };
    }

    // "Process item": run AI validation/normalisation, surface feedback, then reveal "Create request"
    function doProcess(type, materialId, draft) {
        const p = collect();
        const res = window.AI.validate(p);
        document.querySelectorAll('.form-input, .form-select, .search-select input[type="hidden"]').forEach(el => el.classList.remove('error'));
        if (!res.ok) {
            res.blocking.forEach(b => { const el = document.querySelector(`[name="${b.field}"]`); if (el) el.classList.add('error'); });
            renderFeedback(res, true);
            window.UI.toast({ title: 'Fix required fields', body: 'Complete the mandatory fields, then process again.', kind: 'danger' });
            document.getElementById('ai-feedback').scrollIntoView({ behavior: 'smooth', block: 'center' });
            return;
        }
        // AI identification pass: the engine ALWAYS rewrites both descriptions into the
        // MRO structure of the master (profile match or payload-derived), keeps the
        // readable wording on the hidden name field and locks the long description.
        const seed = [p.shortName, p.manufacturer, p.mfrPartNo].filter(Boolean).join(' ');
        const a2 = window.AI.analyze(seed);
        // an item whose descriptions are ALREADY MRO-structured (e.g. amending a
        // mastered record) keeps them verbatim — never re-derive and overwrite
        const alreadyStructured = !/[a-z]/.test(p.shortName || '');
        const sd = alreadyStructured
            ? { shortName: p.shortName, longDesc: p.longDesc }
            : ((a2.known && a2.parsed.longDesc)
                ? { shortName: a2.parsed.shortName, longDesc: a2.parsed.longDesc }
                : window.AI.structuredDesc(p));
        const nameInput = document.querySelector('input[name="name"]');
        if (nameInput && /[a-z]/.test(p.shortName || '') && (!nameInput.value || nameInput.value === p.shortName)) nameInput.value = p.shortName;
        const sn = document.querySelector('[name="shortName"]');
        if (sn && sd.shortName) { sn.value = sd.shortName; sn.classList.add('ai-filled'); }
        const ld = document.querySelector('[name="longDesc"]');
        if (ld && sd.longDesc) {
            ld.value = sd.longDesc;
            ld.setAttribute('readonly', '');
            ld.classList.add('ai-filled');
            const hint = ld.closest('.field') ? ld.closest('.field').querySelector('.hint') : null;
            if (hint) hint.textContent = 'Generated by the AI engine — not editable';
        }
        renderFeedback(res, false);
        const btn = document.getElementById('primary-btn');
        if (btn) btn.outerHTML = `<button class="btn btn-green" id="primary-btn" data-act="submit">${type === 'amend' ? 'Submit amendment' : 'Create request'}</button>`;
        window.UI.toast({ title: 'Item processed', body: res.warnings.length ? 'AI added recommendations below — you can still create the request.' : 'No issues found. Ready to create the request.' });
    }

    function doSubmit(type, materialId, draft) {
        const p = collect();
        const res = window.AI.validate(p);
        // reset field errors
        document.querySelectorAll('.form-input, .form-select, .search-select input[type="hidden"]').forEach(el => el.classList.remove('error'));
        if (!res.ok) {
            res.blocking.forEach(b => { const el = document.querySelector(`[name="${b.field}"]`); if (el) el.classList.add('error'); });
            renderFeedback(res, true);
            window.UI.toast({ title: 'Cannot submit', body: 'Some mandatory fields are blank. Please complete them.', kind: 'danger' });
            document.getElementById('ai-feedback').scrollIntoView({ behavior: 'smooth', block: 'center' });
            return;
        }
        // warnings do not block, but surface them again and require explicit confirmation before creating
        if (res.warnings.length) {
            renderFeedback(res, false);
            window.UI.openModal({
                title: '✦ Please review before creating',
                bodyHtml: `<p class="muted" style="margin-bottom:12px">The AI still has ${res.warnings.length} recommendation(s) for this item. These do not block the request — confirm you want to create it with the current data, or go back to adjust.</p>
                    ${res.warnings.map(w => `<div class="banner ${w.level === 'warn' ? 'warn' : 'info'} mb-0" style="margin-bottom:10px"><span class="banner-icon">${w.level === 'warn' ? '⚠️' : '💡'}</span><div class="banner-body">${esc(w.msg)}</div></div>`).join('')}`,
                buttons: [
                    { label: 'Go back & adjust', cls: 'btn-outline', onClick: (o) => o.remove() },
                    { label: 'Yes, create with this data', cls: 'btn-green', onClick: (o) => { o.remove(); finalize(type, p, materialId, res.warnings, draft); } }
                ]
            });
            return;
        }
        finalize(type, p, materialId, [], draft);
    }

    function finalize(type, payload, materialId, warnings, draft) {
        // resubmit an existing declined/draft request rather than creating a new one
        if (draft && draft.resubmitId) {
            const req = window.Store.requestById(draft.resubmitId);
            if (req) {
                req.aiFeedback = warnings;
                window.Workflow.resubmit(req, payload);
                window.Views._draft = null;
                window.UI.toast({ title: 'Resubmitted', body: 'Sent to ' + firstStageRole(type) + ' for review.', kind: 'info' });
                window.UI.go('#/request/' + req.id);
                return;
            }
        }
        const req = window.Workflow.createRequest({ type, payload, materialId, aiFeedback: warnings });
        const fromBulk = draft && draft.fromBulk ? draft.fromBulk : null;
        window.Views._draft = null;
        window.UI.toast({ title: 'Request submitted', body: 'Sent to ' + firstStageRole(type) + ' for review.', kind: 'info' });
        if (fromBulk) {
            window.Views.bulkMarkAction(fromBulk.batch, fromBulk.i, 'Created — ' + window.Workflow.reqNo(req));
            window.UI.go('#/bulk/' + fromBulk.batch);
            return;
        }
        window.UI.go('#/request/' + req.id);
    }
    function firstStageRole(type) {
        const st = window.Workflow.stagesFor(type)[0];
        return st ? st.role : 'review';
    }

    function renderFeedback(res, submitted) {
        const box = document.getElementById('ai-feedback');
        let html = '';
        if (res.blocking.length) {
            html += `<div class="banner danger"><span class="banner-icon">🚫</span><div class="banner-body">
                <div class="banner-title">${res.blocking.length} mandatory field(s) must be completed before submitting</div>
                <ul style="margin:6px 0 0 18px">${res.blocking.map(b => `<li>${esc(b.msg)}</li>`).join('')}</ul></div></div>`;
        }
        res.warnings.forEach(w => {
            html += `<div class="banner ${w.level === 'warn' ? 'warn' : 'info'}"><span class="banner-icon">${w.level === 'warn' ? '⚠️' : '💡'}</span>
                <div class="banner-body"><div class="banner-title">${w.level === 'warn' ? 'AI warning' : 'AI recommendation'}</div>${esc(w.msg)}</div></div>`;
        });
        if (!html) html = `<div class="banner match"><span class="banner-icon">✓</span><div class="banner-body"><div class="banner-title">Looks good</div>AI found no issues. You can submit this request.</div></div>`;
        box.innerHTML = html;
        box.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }

    /* ================= EXTEND / BLOCK / REACTIVATE confirm ================= */
    function confirmView(type, draft) {
        const root = document.getElementById('view');
        const m = draft && draft.materialId ? window.Store.materialById(draft.materialId) : null;
        if (!m) { root.innerHTML = `<div class="page-narrow"><div class="empty-state">No item selected.</div></div>`; return; }
        const s = window.Store.session();
        const cfg = {
            extend: { title: 'Request for item extension', cta: 'Submit extension',
                note: `This item exists in plant <strong>${esc(m.plants[0])}</strong>. It will be extended to your plant <strong>${esc(s.plant)}</strong>. No approval is required — the system will call SAP immediately.` },
            block: { title: 'Request to block item (plant level)', cta: 'Submit block request',
                note: `This will request blocking <strong>${esc(m.name)}</strong> at plant <strong>${esc(s.plant)}</strong>. It requires MDM Specialist approval before SAP is updated.` },
            reactivate: { title: 'Request to reactivate item', cta: 'Submit reactivation',
                note: `This will request reactivating the blocked item <strong>${esc(m.name)}</strong> at plant <strong>${esc(s.plant)}</strong>. It requires MDM Specialist approval.` }
        }[type];

        root.innerHTML = `
            <div class="page-narrow">
                <div class="back-link" data-act="back">‹ Back</div>
                <div class="form-header">
                    <div class="form-actions">
                        <button class="btn btn-green" data-act="submit">${cfg.cta}</button>
                        <button class="btn btn-outline" data-act="back">Cancel</button>
                    </div>
                </div>
                <h2 class="form-page-title">${esc(cfg.title)}</h2>
                <div class="banner ${type === 'extend' ? 'match' : 'warn'}"><span class="banner-icon">ℹ️</span><div class="banner-body">${cfg.note}</div></div>

                ${type === 'extend' ? `<div class="result-block"><div class="rb-head">
                    <div><div class="k muted" style="font-size:11px;text-transform:uppercase">Source plant (extend from)</div>
                        <div class="rb-title">${esc(window.UI.plantLabel(m.plants[0]))}</div></div>
                    <div style="font-size:22px">→</div>
                    <div style="text-align:right"><div class="k muted" style="font-size:11px;text-transform:uppercase">Target plant (extend to)</div>
                        <div class="rb-title">${esc(window.UI.plantLabel(s.plant))}</div></div>
                </div></div>` : ''}

                <div class="section-title">Technical specifications</div>
                <div class="detail-meta" style="margin-bottom:16px">
                    <div><span class="muted">Short name - </span>${esc(m.shortName || '—')}</div>
                    <div><span class="muted">Long description - </span>${esc(m.longDesc || '—')}</div>
                    <div><span class="muted">Manufacturer - </span>${esc(m.manufacturer || '—')} · <span class="muted">Part # - </span>${esc(m.mfrPartNo || '—')}</div>
                    <div><span class="muted">UNSPSC - </span>${esc(m.unspsc)} · <span class="muted">SAP ID - </span>${esc(m.sapId || '—')} · <span class="muted">Base UoM - </span>${esc(m.baseUom)}</div>
                </div>
                <div style="font-weight:600;margin-bottom:12px">Item attributes</div>
                ${window.UI.techGrid(m.attributes)}
            </div>`;

        window.UI.bindActions(root, {
            'back': () => window.UI.go('#/item/' + m.id),
            'submit': () => {
                const req = window.Workflow.createRequest({ type, payload: payloadFromMaterial(m), materialId: m.id });
                const fromBulk = draft && draft.fromBulk ? draft.fromBulk : null;
                window.Views._draft = null;
                if (type === 'extend') {
                    window.UI.toast({ title: 'Item extended', body: 'SAP ID ' + req.sapId + ' — “' + (m.shortName || m.name) + '” is now available in Plant ' + s.plant + '.', kind: 'info' });
                } else {
                    window.UI.toast({ title: 'Request submitted', body: 'Sent to MDM Specialist for review.', kind: 'info' });
                }
                if (fromBulk) {
                    window.Views.bulkMarkAction(fromBulk.batch, fromBulk.i, type === 'extend' ? 'Extended — SAP ID ' + req.sapId : 'Submitted — ' + window.Workflow.reqNo(req));
                    window.UI.go('#/bulk/' + fromBulk.batch);
                    return;
                }
                window.UI.go('#/request/' + req.id);
            }
        });
    }

    /* ---------------- helpers ---------------- */
    function emptyPayload() {
        const s = window.Store.session();
        return { name: '', shortName: '', longDesc: '', materialType: 'ROH', matTypeChoice: '',
            manufacturer: '', mfrPartNo: '', unspsc: '', unspscLabel: '', category: '', materialGroup: '',
            materialDescription: '', baseUom: '', plants: [s.plant], plant: s.plant, storageLocation: '', mrpEnabled: '',
            batchManaged: '', mrpType: '', recordType: '', valuationClass: '', attributes: {}, image: '' };
    }
    function payloadFromMaterial(m) {
        return {
            name: m.name, shortName: m.shortName, longDesc: m.longDesc, materialType: 'ROH',
            matTypeChoice: m.matTypeChoice, manufacturer: m.manufacturer, mfrPartNo: m.mfrPartNo,
            unspsc: m.unspsc, unspscLabel: m.unspscLabel, category: m.category, materialGroup: m.materialGroup,
            materialDescription: window.UI.groupDesc(m.materialGroup),
            baseUom: m.baseUom,
            plants: (m.plants || []).slice(),
            plant: (m.plants && m.plants[0]) || window.Store.session().plant,
            storageLocation: m.storageLocation, mrpEnabled: m.mrpEnabled, batchManaged: m.batchManaged,
            mrpType: m.mrpType, recordType: m.recordType, valuationClass: m.valuationClass,
            attributes: Object.assign({}, m.attributes), image: m.image
        };
    }
})();
